#
# This file is autogenerated. Please do not edit directly
#
# Last generated by mmcintyr on 21/01/2020 2:56:06 PM
#

function Clear-CsOnlineTelephoneNumberReservation
{
    # Mock stub for Clear-CsOnlineTelephoneNumberReservation
}

function ConvertTo-JsonForPSWS
{
    # Mock stub for ConvertTo-JsonForPSWS
}

function Disable-CsOnlineDialInConferencingUser
{
    # Mock stub for Disable-CsOnlineDialInConferencingUser
}

function Disable-CsOnlineSipDomain
{
    # Mock stub for Disable-CsOnlineSipDomain
}

function Enable-CsOnlineDialInConferencingUser
{
    # Mock stub for Enable-CsOnlineDialInConferencingUser
}

function Enable-CsOnlineSipDomain
{
    # Mock stub for Enable-CsOnlineSipDomain
}

function Export-CsAutoAttendantHolidays
{
    # Mock stub for Export-CsAutoAttendantHolidays
}

function Export-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Export-CsOrganizationalAutoAttendantHolidays
}

function Find-CsGroup
{
    # Mock stub for Find-CsGroup
}

function Find-CsOnlineApplicationInstance
{
    # Mock stub for Find-CsOnlineApplicationInstance
}

function Get-CsAudioConferencingProvider
{
    # Mock stub for Get-CsAudioConferencingProvider
}

function Get-CsAutoAttendant
{
    # Mock stub for Get-CsAutoAttendant
}

function Get-CsAutoAttendantHolidays
{
    # Mock stub for Get-CsAutoAttendantHolidays
}

function Get-CsAutoAttendantStatus
{
    # Mock stub for Get-CsAutoAttendantStatus
}

function Get-CsAutoAttendantSupportedLanguage
{
    # Mock stub for Get-CsAutoAttendantSupportedLanguage
}

function Get-CsAutoAttendantSupportedTimeZone
{
    # Mock stub for Get-CsAutoAttendantSupportedTimeZone
}

function Get-CsAutoAttendantTenantInformation
{
    # Mock stub for Get-CsAutoAttendantTenantInformation
}

function Get-CsBroadcastMeetingConfiguration
{
    # Mock stub for Get-CsBroadcastMeetingConfiguration
}

function Get-CsBroadcastMeetingPolicy
{
    # Mock stub for Get-CsBroadcastMeetingPolicy
}

function Get-CsCallingLineIdentity
{
    # Mock stub for Get-CsCallingLineIdentity
}

function Get-CsCallQueue
{
    # Mock stub for Get-CsCallQueue
}

function Get-CsCloudCallDataConnection
{
    # Mock stub for Get-CsCloudCallDataConnection
}

function Get-CsCloudMeetingPolicy
{
    # Mock stub for Get-CsCloudMeetingPolicy
}

function Get-CsDefaultCatalogApp
{
    # Mock stub for Get-CsDefaultCatalogApp
}

function Get-CsEffectiveTenantDialPlan
{
    # Mock stub for Get-CsEffectiveTenantDialPlan
}

function Get-CsExternalUserCommunicationPolicy
{
    # Mock stub for Get-CsExternalUserCommunicationPolicy
}

function Get-CsGlobalCatalogApp
{
    # Mock stub for Get-CsGlobalCatalogApp
}

function Get-CsGraphPolicy
{
    # Mock stub for Get-CsGraphPolicy
}

function Get-CsHuntGroup
{
    # Mock stub for Get-CsHuntGroup
}

function Get-CsHuntGroupTenantInformation
{
    # Mock stub for Get-CsHuntGroupTenantInformation
}

function Get-CsHybridMediationServer
{
    # Mock stub for Get-CsHybridMediationServer
}

function Get-CsHybridPSTNAppliance
{
    # Mock stub for Get-CsHybridPSTNAppliance
}

function Get-CsHybridPSTNSite
{
    # Mock stub for Get-CsHybridPSTNSite
}

function Get-CsInboundBlockedNumberPattern
{
    # Mock stub for Get-CsInboundBlockedNumberPattern
}

function Get-CsMeetingMigrationStatus
{
    # Mock stub for Get-CsMeetingMigrationStatus
}

function Get-CsOnlineApplicationEndpoint
{
    # Mock stub for Get-CsOnlineApplicationEndpoint
}

function Get-CsOnlineApplicationInstance
{
    # Mock stub for Get-CsOnlineApplicationInstance
}

function Get-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for Get-CsOnlineApplicationInstanceAssociation
}

function Get-CsOnlineApplicationInstanceAssociationStatus
{
    # Mock stub for Get-CsOnlineApplicationInstanceAssociationStatus
}

function Get-CsOnlineDialInConferencingBridge
{
    # Mock stub for Get-CsOnlineDialInConferencingBridge
}

function Get-CsOnlineDialInConferencingLanguagesSupported
{
    # Mock stub for Get-CsOnlineDialInConferencingLanguagesSupported
}

function Get-CsOnlineDialinConferencingPolicy
{
    # Mock stub for Get-CsOnlineDialinConferencingPolicy
}

function Get-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Get-CsOnlineDialInConferencingServiceNumber
}

function Get-CsOnlineDialinConferencingTenantConfiguration
{
    # Mock stub for Get-CsOnlineDialinConferencingTenantConfiguration
}

function Get-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Get-CsOnlineDialInConferencingTenantSettings
}

function Get-CsOnlineDialInConferencingUser
{
    # Mock stub for Get-CsOnlineDialInConferencingUser
}

function Get-CsOnlineDialInConferencingUserInfo
{
    # Mock stub for Get-CsOnlineDialInConferencingUserInfo
}

function Get-CsOnlineDialInConferencingUserState
{
    # Mock stub for Get-CsOnlineDialInConferencingUserState
}

function Get-CsOnlineDialOutPolicy
{
    # Mock stub for Get-CsOnlineDialOutPolicy
}

function Get-CsOnlineDirectoryTenant
{
    # Mock stub for Get-CsOnlineDirectoryTenant
}

function Get-CsOnlineDirectoryTenantNumberCities
{
    # Mock stub for Get-CsOnlineDirectoryTenantNumberCities
}

function Get-CsOnlineEnhancedEmergencyServiceDisclaimer
{
    # Mock stub for Get-CsOnlineEnhancedEmergencyServiceDisclaimer
}

function Get-CsOnlineLisCivicAddress
{
    # Mock stub for Get-CsOnlineLisCivicAddress
}

function Get-CsOnlineLisLocation
{
    # Mock stub for Get-CsOnlineLisLocation
}

function Get-CsOnlineLisPort
{
    # Mock stub for Get-CsOnlineLisPort
}

function Get-CsOnlineLisSubnet
{
    # Mock stub for Get-CsOnlineLisSubnet
}

function Get-CsOnlineLisSwitch
{
    # Mock stub for Get-CsOnlineLisSwitch
}

function Get-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Get-CsOnlineLisWirelessAccessPoint
}

function Get-CsOnlineNumberPortInOrder
{
    # Mock stub for Get-CsOnlineNumberPortInOrder
}

function Get-CsOnlineNumberPortOutOrderPin
{
    # Mock stub for Get-CsOnlineNumberPortOutOrderPin
}

function Get-CsOnlinePSTNGateway
{
    # Mock stub for Get-CsOnlinePSTNGateway
}

function Get-CsOnlinePstnUsage
{
    # Mock stub for Get-CsOnlinePstnUsage
}

function Get-CsOnlineSchedule
{
    # Mock stub for Get-CsOnlineSchedule
}

function Get-CsOnlineSipDomain
{
    # Mock stub for Get-CsOnlineSipDomain
}

function Get-CsOnlineTelephoneNumber
{
    # Mock stub for Get-CsOnlineTelephoneNumber
}

function Get-CsOnlineTelephoneNumberAvailableCount
{
    # Mock stub for Get-CsOnlineTelephoneNumberAvailableCount
}

function Get-CsOnlineTelephoneNumberInventoryAreas
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryAreas
}

function Get-CsOnlineTelephoneNumberInventoryCities
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryCities
}

function Get-CsOnlineTelephoneNumberInventoryCountries
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryCountries
}

function Get-CsOnlineTelephoneNumberInventoryRegions
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryRegions
}

function Get-CsOnlineTelephoneNumberInventoryTypes
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryTypes
}

function Get-CsOnlineTelephoneNumberReservationsInformation
{
    # Mock stub for Get-CsOnlineTelephoneNumberReservationsInformation
}

function Get-CsOnlineUser
{
    # Mock stub for Get-CsOnlineUser
}

function Get-CsOnlineVoicemailPolicy
{
    # Mock stub for Get-CsOnlineVoicemailPolicy
}

function Get-CsOnlineVoicemailUserSettings
{
    # Mock stub for Get-CsOnlineVoicemailUserSettings
}

function Get-CsOnlineVoiceRoute
{
    # Mock stub for Get-CsOnlineVoiceRoute
}

function Get-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Get-CsOnlineVoiceRoutingPolicy
}

function Get-CsOnlineVoiceUser
{
    # Mock stub for Get-CsOnlineVoiceUser
}

function Get-CsOrganizationalAutoAttendant
{
    # Mock stub for Get-CsOrganizationalAutoAttendant
}

function Get-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Get-CsOrganizationalAutoAttendantHolidays
}

function Get-CsOrganizationalAutoAttendantStatus
{
    # Mock stub for Get-CsOrganizationalAutoAttendantStatus
}

function Get-CsOrganizationalAutoAttendantSupportedLanguage
{
    # Mock stub for Get-CsOrganizationalAutoAttendantSupportedLanguage
}

function Get-CsOrganizationalAutoAttendantSupportedTimeZone
{
    # Mock stub for Get-CsOrganizationalAutoAttendantSupportedTimeZone
}

function Get-CsOrganizationalAutoAttendantTenantInformation
{
    # Mock stub for Get-CsOrganizationalAutoAttendantTenantInformation
}

function Get-CsTeamsAppPermissionPolicy
{
    # Mock stub for Get-CsTeamsAppPermissionPolicy
}

function Get-CsTeamsAppSetupPolicy
{
    # Mock stub for Get-CsTeamsAppSetupPolicy
}

function Get-CsTeamsCallingPolicy
{
    # Mock stub for Get-CsTeamsCallingPolicy
}

function Get-CsTeamsCallParkPolicy
{
    # Mock stub for Get-CsTeamsCallParkPolicy
}

function Get-CsTeamsChannelsPolicy
{
    # Mock stub for Get-CsTeamsChannelsPolicy
}

function Get-CsTeamsClientConfiguration
{
    # Mock stub for Get-CsTeamsClientConfiguration
}

function Get-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Get-CsTeamsComplianceRecordingApplication
}

function Get-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Get-CsTeamsComplianceRecordingPolicy
}

function Get-CsTeamsEducationAssignmentsAppPolicy
{
    # Mock stub for Get-CsTeamsEducationAssignmentsAppPolicy
}

function Get-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Get-CsTeamsEmergencyCallingPolicy
}

function Get-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Get-CsTeamsEmergencyCallRoutingPolicy
}

function Get-CsTeamsFeedbackPolicy
{
    # Mock stub for Get-CsTeamsFeedbackPolicy
}

function Get-CsTeamsGuestCallingConfiguration
{
    # Mock stub for Get-CsTeamsGuestCallingConfiguration
}

function Get-CsTeamsGuestMeetingConfiguration
{
    # Mock stub for Get-CsTeamsGuestMeetingConfiguration
}

function Get-CsTeamsGuestMessagingConfiguration
{
    # Mock stub for Get-CsTeamsGuestMessagingConfiguration
}

function Get-CsTeamsIPPhonePolicy
{
    # Mock stub for Get-CsTeamsIPPhonePolicy
}

function Get-CsTeamsMeetingBroadcastConfiguration
{
    # Mock stub for Get-CsTeamsMeetingBroadcastConfiguration
}

function Get-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Get-CsTeamsMeetingBroadcastPolicy
}

function Get-CsTeamsMeetingConfiguration
{
    # Mock stub for Get-CsTeamsMeetingConfiguration
}

function Get-CsTeamsMeetingPolicy
{
    # Mock stub for Get-CsTeamsMeetingPolicy
}

function Get-CsTeamsMessagingPolicy
{
    # Mock stub for Get-CsTeamsMessagingPolicy
}

function Get-CsTeamsMigrationConfiguration
{
    # Mock stub for Get-CsTeamsMigrationConfiguration
}

function Get-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Get-CsTeamsNotificationAndFeedsPolicy
}

function Get-CsTeamsPinnedApp
{
    # Mock stub for Get-CsTeamsPinnedApp
}

function Get-CsTeamsTranslationRule
{
    # Mock stub for Get-CsTeamsTranslationRule
}

function Get-CsTeamsUpgradeStatus
{
    # Mock stub for Get-CsTeamsUpgradeStatus
}

function Get-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Get-CsTeamsVerticalPackagePolicy
}

function Get-CsTeamsVideoInteropServicePolicy
{
    # Mock stub for Get-CsTeamsVideoInteropServicePolicy
}

function Get-CsTenant
{
    # Mock stub for Get-CsTenant
}

function Get-CsTenantBlockedCallingNumbers
{
    # Mock stub for Get-CsTenantBlockedCallingNumbers
}

function Get-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Get-CsTenantBlockedNumberExceptionPattern
}

function Get-CsTenantCatalogApp
{
    # Mock stub for Get-CsTenantCatalogApp
}

function Get-CsTenantDialPlan
{
    # Mock stub for Get-CsTenantDialPlan
}

function Get-CsTenantFederationConfiguration
{
    # Mock stub for Get-CsTenantFederationConfiguration
}

function Get-CsTenantLicensingConfiguration
{
    # Mock stub for Get-CsTenantLicensingConfiguration
}

function Get-CsTenantMigrationConfiguration
{
    # Mock stub for Get-CsTenantMigrationConfiguration
}

function Get-CsTenantNetworkConfiguration
{
    # Mock stub for Get-CsTenantNetworkConfiguration
}

function Get-CsTenantNetworkRegion
{
    # Mock stub for Get-CsTenantNetworkRegion
}

function Get-CsTenantNetworkSite
{
    # Mock stub for Get-CsTenantNetworkSite
}

function Get-CsTenantNetworkSubnet
{
    # Mock stub for Get-CsTenantNetworkSubnet
}

function Get-CsTenantPublicProvider
{
    # Mock stub for Get-CsTenantPublicProvider
}

function Get-CsTenantTrustedIPAddress
{
    # Mock stub for Get-CsTenantTrustedIPAddress
}

function Get-CsTenantUpdateTimeWindow
{
    # Mock stub for Get-CsTenantUpdateTimeWindow
}

function Get-CsUserLocationStatus
{
    # Mock stub for Get-CsUserLocationStatus
}

function Get-CsUserPstnSettings
{
    # Mock stub for Get-CsUserPstnSettings
}

function Get-CsUserSession
{
    # Mock stub for Get-CsUserSession
}

function Get-CsVideoInteropServiceProvider
{
    # Mock stub for Get-CsVideoInteropServiceProvider
}

function Grant-CsBroadcastMeetingPolicy
{
    # Mock stub for Grant-CsBroadcastMeetingPolicy
}

function Grant-CsCallingLineIdentity
{
    # Mock stub for Grant-CsCallingLineIdentity
}

function Grant-CsCloudMeetingPolicy
{
    # Mock stub for Grant-CsCloudMeetingPolicy
}

function Grant-CsExternalUserCommunicationPolicy
{
    # Mock stub for Grant-CsExternalUserCommunicationPolicy
}

function Grant-CsGraphPolicy
{
    # Mock stub for Grant-CsGraphPolicy
}

function Grant-CsOnlineVoicemailPolicy
{
    # Mock stub for Grant-CsOnlineVoicemailPolicy
}

function Grant-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Grant-CsOnlineVoiceRoutingPolicy
}

function Grant-CsPolicy
{
    # Mock stub for Grant-CsPolicy
}

function Grant-CsTeamsAppPermissionPolicy
{
    # Mock stub for Grant-CsTeamsAppPermissionPolicy
}

function Grant-CsTeamsAppSetupPolicy
{
    # Mock stub for Grant-CsTeamsAppSetupPolicy
}

function Grant-CsTeamsCallingPolicy
{
    # Mock stub for Grant-CsTeamsCallingPolicy
}

function Grant-CsTeamsCallParkPolicy
{
    # Mock stub for Grant-CsTeamsCallParkPolicy
}

function Grant-CsTeamsChannelsPolicy
{
    # Mock stub for Grant-CsTeamsChannelsPolicy
}

function Grant-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Grant-CsTeamsComplianceRecordingPolicy
}

function Grant-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Grant-CsTeamsEmergencyCallingPolicy
}

function Grant-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Grant-CsTeamsEmergencyCallRoutingPolicy
}

function Grant-CsTeamsFeedbackPolicy
{
    # Mock stub for Grant-CsTeamsFeedbackPolicy
}

function Grant-CsTeamsIPPhonePolicy
{
    # Mock stub for Grant-CsTeamsIPPhonePolicy
}

function Grant-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Grant-CsTeamsMeetingBroadcastPolicy
}

function Grant-CsTeamsMeetingPolicy
{
    # Mock stub for Grant-CsTeamsMeetingPolicy
}

function Grant-CsTeamsMessagingPolicy
{
    # Mock stub for Grant-CsTeamsMessagingPolicy
}

function Grant-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Grant-CsTeamsVerticalPackagePolicy
}

function Grant-CsTeamsVideoInteropServicePolicy
{
    # Mock stub for Grant-CsTeamsVideoInteropServicePolicy
}

function Grant-CsTenantDialPlan
{
    # Mock stub for Grant-CsTenantDialPlan
}

function Import-CsAutoAttendantHolidays
{
    # Mock stub for Import-CsAutoAttendantHolidays
}

function Import-CsOnlineAudioFile
{
    # Mock stub for Import-CsOnlineAudioFile
}

function Import-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Import-CsOrganizationalAutoAttendantHolidays
}

function Invoke-CsUserPreferredDataLocationSync
{
    # Mock stub for Invoke-CsUserPreferredDataLocationSync
}

function New-CsAutoAttendant
{
    # Mock stub for New-CsAutoAttendant
}

function New-CsAutoAttendantCallableEntity
{
    # Mock stub for New-CsAutoAttendantCallableEntity
}

function New-CsAutoAttendantCallFlow
{
    # Mock stub for New-CsAutoAttendantCallFlow
}

function New-CsAutoAttendantCallHandlingAssociation
{
    # Mock stub for New-CsAutoAttendantCallHandlingAssociation
}

function New-CsAutoAttendantDialScope
{
    # Mock stub for New-CsAutoAttendantDialScope
}

function New-CsAutoAttendantMenu
{
    # Mock stub for New-CsAutoAttendantMenu
}

function New-CsAutoAttendantMenuOption
{
    # Mock stub for New-CsAutoAttendantMenuOption
}

function New-CsAutoAttendantPrompt
{
    # Mock stub for New-CsAutoAttendantPrompt
}

function New-CsCallingLineIdentity
{
    # Mock stub for New-CsCallingLineIdentity
}

function New-CsCallQueue
{
    # Mock stub for New-CsCallQueue
}

function New-CsCloudCallDataConnection
{
    # Mock stub for New-CsCloudCallDataConnection
}

function New-CsDefaultCatalogApp
{
    # Mock stub for New-CsDefaultCatalogApp
}

function New-CsEdgeAllowAllKnownDomains
{
    # Mock stub for New-CsEdgeAllowAllKnownDomains
}

function New-CsEdgeAllowList
{
    # Mock stub for New-CsEdgeAllowList
}

function New-CsEdgeDomainPattern
{
    # Mock stub for New-CsEdgeDomainPattern
}

function New-CsExternalUserCommunicationPolicy
{
    # Mock stub for New-CsExternalUserCommunicationPolicy
}

function New-CsGlobalCatalogApp
{
    # Mock stub for New-CsGlobalCatalogApp
}

function New-CsHuntGroup
{
    # Mock stub for New-CsHuntGroup
}

function New-CsHybridPSTNSite
{
    # Mock stub for New-CsHybridPSTNSite
}

function New-CsHybridTelephoneNumber
{
    # Mock stub for New-CsHybridTelephoneNumber
}

function New-CsInboundBlockedNumberPattern
{
    # Mock stub for New-CsInboundBlockedNumberPattern
}

function New-CsOnlineApplicationEndpoint
{
    # Mock stub for New-CsOnlineApplicationEndpoint
}

function New-CsOnlineApplicationInstance
{
    # Mock stub for New-CsOnlineApplicationInstance
}

function New-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for New-CsOnlineApplicationInstanceAssociation
}

function New-CsOnlineAudioFile
{
    # Mock stub for New-CsOnlineAudioFile
}

function New-CsOnlineBulkAssignmentInput
{
    # Mock stub for New-CsOnlineBulkAssignmentInput
}

function New-CsOnlineDateTimeRange
{
    # Mock stub for New-CsOnlineDateTimeRange
}

function New-CsOnlineLisCivicAddress
{
    # Mock stub for New-CsOnlineLisCivicAddress
}

function New-CsOnlineLisLocation
{
    # Mock stub for New-CsOnlineLisLocation
}

function New-CsOnlineNumberPortInOrder
{
    # Mock stub for New-CsOnlineNumberPortInOrder
}

function New-CsOnlinePSTNGateway
{
    # Mock stub for New-CsOnlinePSTNGateway
}

function New-CsOnlineSchedule
{
    # Mock stub for New-CsOnlineSchedule
}

function New-CsOnlineTimeRange
{
    # Mock stub for New-CsOnlineTimeRange
}

function New-CsOnlineVoicemailPolicy
{
    # Mock stub for New-CsOnlineVoicemailPolicy
}

function New-CsOnlineVoiceRoute
{
    # Mock stub for New-CsOnlineVoiceRoute
}

function New-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for New-CsOnlineVoiceRoutingPolicy
}

function New-CsOrganizationalAutoAttendant
{
    # Mock stub for New-CsOrganizationalAutoAttendant
}

function New-CsOrganizationalAutoAttendantCallableEntity
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallableEntity
}

function New-CsOrganizationalAutoAttendantCallFlow
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallFlow
}

function New-CsOrganizationalAutoAttendantCallHandlingAssociation
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallHandlingAssociation
}

function New-CsOrganizationalAutoAttendantDialScope
{
    # Mock stub for New-CsOrganizationalAutoAttendantDialScope
}

function New-CsOrganizationalAutoAttendantMenu
{
    # Mock stub for New-CsOrganizationalAutoAttendantMenu
}

function New-CsOrganizationalAutoAttendantMenuOption
{
    # Mock stub for New-CsOrganizationalAutoAttendantMenuOption
}

function New-CsOrganizationalAutoAttendantPrompt
{
    # Mock stub for New-CsOrganizationalAutoAttendantPrompt
}

function New-CsTeamsAppPermissionPolicy
{
    # Mock stub for New-CsTeamsAppPermissionPolicy
}

function New-CsTeamsAppSetupPolicy
{
    # Mock stub for New-CsTeamsAppSetupPolicy
}

function New-CsTeamsCallingPolicy
{
    # Mock stub for New-CsTeamsCallingPolicy
}

function New-CsTeamsCallParkPolicy
{
    # Mock stub for New-CsTeamsCallParkPolicy
}

function New-CsTeamsChannelsPolicy
{
    # Mock stub for New-CsTeamsChannelsPolicy
}

function New-CsTeamsComplianceRecordingApplication
{
    # Mock stub for New-CsTeamsComplianceRecordingApplication
}

function New-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for New-CsTeamsComplianceRecordingPolicy
}

function New-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for New-CsTeamsEmergencyCallingPolicy
}

function New-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for New-CsTeamsEmergencyCallRoutingPolicy
}

function New-CsTeamsEmergencyNumber
{
    # Mock stub for New-CsTeamsEmergencyNumber
}

function New-CsTeamsFeedbackPolicy
{
    # Mock stub for New-CsTeamsFeedbackPolicy
}

function New-CsTeamsIPPhonePolicy
{
    # Mock stub for New-CsTeamsIPPhonePolicy
}

function New-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for New-CsTeamsMeetingBroadcastPolicy
}

function New-CsTeamsMeetingPolicy
{
    # Mock stub for New-CsTeamsMeetingPolicy
}

function New-CsTeamsMessagingPolicy
{
    # Mock stub for New-CsTeamsMessagingPolicy
}

function New-CsTeamsPinnedApp
{
    # Mock stub for New-CsTeamsPinnedApp
}

function New-CsTeamsTranslationRule
{
    # Mock stub for New-CsTeamsTranslationRule
}

function New-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for New-CsTenantBlockedNumberExceptionPattern
}

function New-CsTenantCatalogApp
{
    # Mock stub for New-CsTenantCatalogApp
}

function New-CsTenantDialPlan
{
    # Mock stub for New-CsTenantDialPlan
}

function New-CsTenantNetworkRegion
{
    # Mock stub for New-CsTenantNetworkRegion
}

function New-CsTenantNetworkSite
{
    # Mock stub for New-CsTenantNetworkSite
}

function New-CsTenantNetworkSubnet
{
    # Mock stub for New-CsTenantNetworkSubnet
}

function New-CsTenantTrustedIPAddress
{
    # Mock stub for New-CsTenantTrustedIPAddress
}

function New-CsTenantUpdateTimeWindow
{
    # Mock stub for New-CsTenantUpdateTimeWindow
}

function New-CsVideoInteropServiceProvider
{
    # Mock stub for New-CsVideoInteropServiceProvider
}

function Register-CsHybridPSTNAppliance
{
    # Mock stub for Register-CsHybridPSTNAppliance
}

function Register-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Register-CsOnlineDialInConferencingServiceNumber
}

function Remove-CsAutoAttendant
{
    # Mock stub for Remove-CsAutoAttendant
}

function Remove-CsCallingLineIdentity
{
    # Mock stub for Remove-CsCallingLineIdentity
}

function Remove-CsCallQueue
{
    # Mock stub for Remove-CsCallQueue
}

function Remove-CsDefaultCatalogApp
{
    # Mock stub for Remove-CsDefaultCatalogApp
}

function Remove-CsExternalUserCommunicationPolicy
{
    # Mock stub for Remove-CsExternalUserCommunicationPolicy
}

function Remove-CsGlobalCatalogApp
{
    # Mock stub for Remove-CsGlobalCatalogApp
}

function Remove-CsHuntGroup
{
    # Mock stub for Remove-CsHuntGroup
}

function Remove-CsHybridPSTNSite
{
    # Mock stub for Remove-CsHybridPSTNSite
}

function Remove-CsHybridTelephoneNumber
{
    # Mock stub for Remove-CsHybridTelephoneNumber
}

function Remove-CsInboundBlockedNumberPattern
{
    # Mock stub for Remove-CsInboundBlockedNumberPattern
}

function Remove-CsOnlineApplicationEndpoint
{
    # Mock stub for Remove-CsOnlineApplicationEndpoint
}

function Remove-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for Remove-CsOnlineApplicationInstanceAssociation
}

function Remove-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Remove-CsOnlineDialInConferencingTenantSettings
}

function Remove-CsOnlineLisCivicAddress
{
    # Mock stub for Remove-CsOnlineLisCivicAddress
}

function Remove-CsOnlineLisLocation
{
    # Mock stub for Remove-CsOnlineLisLocation
}

function Remove-CsOnlineLisPort
{
    # Mock stub for Remove-CsOnlineLisPort
}

function Remove-CsOnlineLisSubnet
{
    # Mock stub for Remove-CsOnlineLisSubnet
}

function Remove-CsOnlineLisSwitch
{
    # Mock stub for Remove-CsOnlineLisSwitch
}

function Remove-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Remove-CsOnlineLisWirelessAccessPoint
}

function Remove-CsOnlineNumberPortInOrder
{
    # Mock stub for Remove-CsOnlineNumberPortInOrder
}

function Remove-CsOnlinePSTNGateway
{
    # Mock stub for Remove-CsOnlinePSTNGateway
}

function Remove-CsOnlineSchedule
{
    # Mock stub for Remove-CsOnlineSchedule
}

function Remove-CsOnlineTelephoneNumber
{
    # Mock stub for Remove-CsOnlineTelephoneNumber
}

function Remove-CsOnlineVoicemailPolicy
{
    # Mock stub for Remove-CsOnlineVoicemailPolicy
}

function Remove-CsOnlineVoiceRoute
{
    # Mock stub for Remove-CsOnlineVoiceRoute
}

function Remove-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Remove-CsOnlineVoiceRoutingPolicy
}

function Remove-CsOrganizationalAutoAttendant
{
    # Mock stub for Remove-CsOrganizationalAutoAttendant
}

function Remove-CsTeamsAppPermissionPolicy
{
    # Mock stub for Remove-CsTeamsAppPermissionPolicy
}

function Remove-CsTeamsAppSetupPolicy
{
    # Mock stub for Remove-CsTeamsAppSetupPolicy
}

function Remove-CsTeamsCallingPolicy
{
    # Mock stub for Remove-CsTeamsCallingPolicy
}

function Remove-CsTeamsCallParkPolicy
{
    # Mock stub for Remove-CsTeamsCallParkPolicy
}

function Remove-CsTeamsChannelsPolicy
{
    # Mock stub for Remove-CsTeamsChannelsPolicy
}

function Remove-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Remove-CsTeamsComplianceRecordingApplication
}

function Remove-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Remove-CsTeamsComplianceRecordingPolicy
}

function Remove-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Remove-CsTeamsEmergencyCallingPolicy
}

function Remove-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Remove-CsTeamsEmergencyCallRoutingPolicy
}

function Remove-CsTeamsFeedbackPolicy
{
    # Mock stub for Remove-CsTeamsFeedbackPolicy
}

function Remove-CsTeamsIPPhonePolicy
{
    # Mock stub for Remove-CsTeamsIPPhonePolicy
}

function Remove-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Remove-CsTeamsMeetingBroadcastPolicy
}

function Remove-CsTeamsMeetingPolicy
{
    # Mock stub for Remove-CsTeamsMeetingPolicy
}

function Remove-CsTeamsMessagingPolicy
{
    # Mock stub for Remove-CsTeamsMessagingPolicy
}

function Remove-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Remove-CsTeamsNotificationAndFeedsPolicy
}

function Remove-CsTeamsPinnedApp
{
    # Mock stub for Remove-CsTeamsPinnedApp
}

function Remove-CsTeamsTranslationRule
{
    # Mock stub for Remove-CsTeamsTranslationRule
}

function Remove-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Remove-CsTenantBlockedNumberExceptionPattern
}

function Remove-CsTenantCatalogApp
{
    # Mock stub for Remove-CsTenantCatalogApp
}

function Remove-CsTenantDialPlan
{
    # Mock stub for Remove-CsTenantDialPlan
}

function Remove-CsTenantNetworkConfiguration
{
    # Mock stub for Remove-CsTenantNetworkConfiguration
}

function Remove-CsTenantNetworkRegion
{
    # Mock stub for Remove-CsTenantNetworkRegion
}

function Remove-CsTenantNetworkSite
{
    # Mock stub for Remove-CsTenantNetworkSite
}

function Remove-CsTenantNetworkSubnet
{
    # Mock stub for Remove-CsTenantNetworkSubnet
}

function Remove-CsTenantTrustedIPAddress
{
    # Mock stub for Remove-CsTenantTrustedIPAddress
}

function Remove-CsTenantUpdateTimeWindow
{
    # Mock stub for Remove-CsTenantUpdateTimeWindow
}

function Remove-CsVideoInteropServiceProvider
{
    # Mock stub for Remove-CsVideoInteropServiceProvider
}

function Search-CsOnlineTelephoneNumberInventory
{
    # Mock stub for Search-CsOnlineTelephoneNumberInventory
}

function Select-CsOnlineTelephoneNumberInventory
{
    # Mock stub for Select-CsOnlineTelephoneNumberInventory
}

function Set-CsAutoAttendant
{
    # Mock stub for Set-CsAutoAttendant
}

function Set-CsBroadcastMeetingConfiguration
{
    # Mock stub for Set-CsBroadcastMeetingConfiguration
}

function Set-CsCallingLineIdentity
{
    # Mock stub for Set-CsCallingLineIdentity
}

function Set-CsCallQueue
{
    # Mock stub for Set-CsCallQueue
}

function Set-CsCceApplianceConfigurationReplicationStatus
{
    # Mock stub for Set-CsCceApplianceConfigurationReplicationStatus
}

function Set-CsCceApplianceDeploymentStatus
{
    # Mock stub for Set-CsCceApplianceDeploymentStatus
}

function Set-CsCceApplianceStatus
{
    # Mock stub for Set-CsCceApplianceStatus
}

function Set-CsDefaultCatalogApp
{
    # Mock stub for Set-CsDefaultCatalogApp
}

function Set-CsExternalUserCommunicationPolicy
{
    # Mock stub for Set-CsExternalUserCommunicationPolicy
}

function Set-CsGlobalCatalogApp
{
    # Mock stub for Set-CsGlobalCatalogApp
}

function Set-CsHuntGroup
{
    # Mock stub for Set-CsHuntGroup
}

function Set-CsHybridMediationServer
{
    # Mock stub for Set-CsHybridMediationServer
}

function Set-CsHybridPSTNAppliance
{
    # Mock stub for Set-CsHybridPSTNAppliance
}

function Set-CsHybridPSTNSite
{
    # Mock stub for Set-CsHybridPSTNSite
}

function Set-CsInboundBlockedNumberPattern
{
    # Mock stub for Set-CsInboundBlockedNumberPattern
}

function Set-CsOnlineApplicationEndpoint
{
    # Mock stub for Set-CsOnlineApplicationEndpoint
}

function Set-CsOnlineApplicationInstance
{
    # Mock stub for Set-CsOnlineApplicationInstance
}

function Set-CsOnlineDialInConferencingBridge
{
    # Mock stub for Set-CsOnlineDialInConferencingBridge
}

function Set-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Set-CsOnlineDialInConferencingServiceNumber
}

function Set-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Set-CsOnlineDialInConferencingTenantSettings
}

function Set-CsOnlineDialInConferencingUser
{
    # Mock stub for Set-CsOnlineDialInConferencingUser
}

function Set-CsOnlineDialInConferencingUserDefaultNumber
{
    # Mock stub for Set-CsOnlineDialInConferencingUserDefaultNumber
}

function Set-CsOnlineDirectoryUser
{
    # Mock stub for Set-CsOnlineDirectoryUser
}

function Set-CsOnlineEnhancedEmergencyServiceDisclaimer
{
    # Mock stub for Set-CsOnlineEnhancedEmergencyServiceDisclaimer
}

function Set-CsOnlineLisCivicAddress
{
    # Mock stub for Set-CsOnlineLisCivicAddress
}

function Set-CsOnlineLisLocation
{
    # Mock stub for Set-CsOnlineLisLocation
}

function Set-CsOnlineLisPort
{
    # Mock stub for Set-CsOnlineLisPort
}

function Set-CsOnlineLisSubnet
{
    # Mock stub for Set-CsOnlineLisSubnet
}

function Set-CsOnlineLisSwitch
{
    # Mock stub for Set-CsOnlineLisSwitch
}

function Set-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Set-CsOnlineLisWirelessAccessPoint
}

function Set-CsOnlineNumberPortInOrder
{
    # Mock stub for Set-CsOnlineNumberPortInOrder
}

function Set-CsOnlineNumberPortOutOrderPin
{
    # Mock stub for Set-CsOnlineNumberPortOutOrderPin
}

function Set-CsOnlinePSTNGateway
{
    # Mock stub for Set-CsOnlinePSTNGateway
}

function Set-CsOnlinePstnUsage
{
    # Mock stub for Set-CsOnlinePstnUsage
}

function Set-CsOnlineSchedule
{
    # Mock stub for Set-CsOnlineSchedule
}

function Set-CsOnlineVoiceApplicationInstance
{
    # Mock stub for Set-CsOnlineVoiceApplicationInstance
}

function Set-CsOnlineVoicemailPolicy
{
    # Mock stub for Set-CsOnlineVoicemailPolicy
}

function Set-CsOnlineVoicemailUserSettings
{
    # Mock stub for Set-CsOnlineVoicemailUserSettings
}

function Set-CsOnlineVoiceRoute
{
    # Mock stub for Set-CsOnlineVoiceRoute
}

function Set-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Set-CsOnlineVoiceRoutingPolicy
}

function Set-CsOnlineVoiceUser
{
    # Mock stub for Set-CsOnlineVoiceUser
}

function Set-CsOnlineVoiceUserBulk
{
    # Mock stub for Set-CsOnlineVoiceUserBulk
}

function Set-CsOrganizationalAutoAttendant
{
    # Mock stub for Set-CsOrganizationalAutoAttendant
}

function Set-CsTeamsAppPermissionPolicy
{
    # Mock stub for Set-CsTeamsAppPermissionPolicy
}

function Set-CsTeamsAppSetupPolicy
{
    # Mock stub for Set-CsTeamsAppSetupPolicy
}

function Set-CsTeamsCallingPolicy
{
    # Mock stub for Set-CsTeamsCallingPolicy
}

function Set-CsTeamsCallParkPolicy
{
    # Mock stub for Set-CsTeamsCallParkPolicy
}

function Set-CsTeamsChannelsPolicy
{
    # Mock stub for Set-CsTeamsChannelsPolicy
}

function Set-CsTeamsClientConfiguration
{
    # Mock stub for Set-CsTeamsClientConfiguration
}

function Set-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Set-CsTeamsComplianceRecordingApplication
}

function Set-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Set-CsTeamsComplianceRecordingPolicy
}

function Set-CsTeamsEducationAssignmentsAppPolicy
{
    # Mock stub for Set-CsTeamsEducationAssignmentsAppPolicy
}

function Set-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Set-CsTeamsEmergencyCallingPolicy
}

function Set-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Set-CsTeamsEmergencyCallRoutingPolicy
}

function Set-CsTeamsFeedbackPolicy
{
    # Mock stub for Set-CsTeamsFeedbackPolicy
}

function Set-CsTeamsGuestCallingConfiguration
{
    # Mock stub for Set-CsTeamsGuestCallingConfiguration
}

function Set-CsTeamsGuestMeetingConfiguration
{
    # Mock stub for Set-CsTeamsGuestMeetingConfiguration
}

function Set-CsTeamsGuestMessagingConfiguration
{
    # Mock stub for Set-CsTeamsGuestMessagingConfiguration
}

function Set-CsTeamsIPPhonePolicy
{
    # Mock stub for Set-CsTeamsIPPhonePolicy
}

function Set-CsTeamsMeetingBroadcastConfiguration
{
    # Mock stub for Set-CsTeamsMeetingBroadcastConfiguration
}

function Set-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Set-CsTeamsMeetingBroadcastPolicy
}

function Set-CsTeamsMeetingConfiguration
{
    # Mock stub for Set-CsTeamsMeetingConfiguration
}

function Set-CsTeamsMeetingPolicy
{
    # Mock stub for Set-CsTeamsMeetingPolicy
}

function Set-CsTeamsMessagingPolicy
{
    # Mock stub for Set-CsTeamsMessagingPolicy
}

function Set-CsTeamsMigrationConfiguration
{
    # Mock stub for Set-CsTeamsMigrationConfiguration
}

function Set-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Set-CsTeamsNotificationAndFeedsPolicy
}

function Set-CsTeamsPinnedApp
{
    # Mock stub for Set-CsTeamsPinnedApp
}

function Set-CsTeamsTranslationRule
{
    # Mock stub for Set-CsTeamsTranslationRule
}

function Set-CsTeamsUpgradeStatus
{
    # Mock stub for Set-CsTeamsUpgradeStatus
}

function Set-CsTenantBlockedCallingNumbers
{
    # Mock stub for Set-CsTenantBlockedCallingNumbers
}

function Set-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Set-CsTenantBlockedNumberExceptionPattern
}

function Set-CsTenantCatalogApp
{
    # Mock stub for Set-CsTenantCatalogApp
}

function Set-CsTenantDialPlan
{
    # Mock stub for Set-CsTenantDialPlan
}

function Set-CsTenantFederationConfiguration
{
    # Mock stub for Set-CsTenantFederationConfiguration
}

function Set-CsTenantMigrationConfiguration
{
    # Mock stub for Set-CsTenantMigrationConfiguration
}

function Set-CsTenantNetworkConfiguration
{
    # Mock stub for Set-CsTenantNetworkConfiguration
}

function Set-CsTenantNetworkRegion
{
    # Mock stub for Set-CsTenantNetworkRegion
}

function Set-CsTenantNetworkSite
{
    # Mock stub for Set-CsTenantNetworkSite
}

function Set-CsTenantNetworkSubnet
{
    # Mock stub for Set-CsTenantNetworkSubnet
}

function Set-CsTenantPublicProvider
{
    # Mock stub for Set-CsTenantPublicProvider
}

function Set-CsTenantTrustedIPAddress
{
    # Mock stub for Set-CsTenantTrustedIPAddress
}

function Set-CsTenantUpdateTimeWindow
{
    # Mock stub for Set-CsTenantUpdateTimeWindow
}

function Set-CsUserPstnSettings
{
    # Mock stub for Set-CsUserPstnSettings
}

function Set-CsVideoInteropServiceProvider
{
    # Mock stub for Set-CsVideoInteropServiceProvider
}

function Start-CsExMeetingMigration
{
    # Mock stub for Start-CsExMeetingMigration
}

function Switch-CsOnlineApplicationEndpoint
{
    # Mock stub for Switch-CsOnlineApplicationEndpoint
}

function Sync-CsOnlineApplicationInstance
{
    # Mock stub for Sync-CsOnlineApplicationInstance
}

function Test-CsEffectiveTenantDialPlan
{
    # Mock stub for Test-CsEffectiveTenantDialPlan
}

function Test-CsInboundBlockedNumberPattern
{
    # Mock stub for Test-CsInboundBlockedNumberPattern
}

function Test-CsOnlineCarrierPortabilityIn
{
    # Mock stub for Test-CsOnlineCarrierPortabilityIn
}

function Test-CsOnlineLisCivicAddress
{
    # Mock stub for Test-CsOnlineLisCivicAddress
}

function Test-CsOnlinePortabilityIn
{
    # Mock stub for Test-CsOnlinePortabilityIn
}

function Unregister-CsHybridPSTNAppliance
{
    # Mock stub for Unregister-CsHybridPSTNAppliance
}

function Unregister-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Unregister-CsOnlineDialInConferencingServiceNumber
}

function Update-CsAutoAttendant
{
    # Mock stub for Update-CsAutoAttendant
}

function Update-CsOrganizationalAutoAttendant
{
    # Mock stub for Update-CsOrganizationalAutoAttendant
}

function Update-CsTenantMeetingUrl
{
    # Mock stub for Update-CsTenantMeetingUrl
}

