#
# This file is autogenerated. Please do not edit directly
#
# Last generated by mmcintyr on 26/10/2020 5:06:56 PM
#

function Add-MsolAdministrativeUnitMember
{
    # Mock stub for Add-MsolAdministrativeUnitMember
}

function Add-MsolForeignGroupToRole
{
    # Mock stub for Add-MsolForeignGroupToRole
}

function Add-MsolGroupMember
{
    # Mock stub for Add-MsolGroupMember
}

function Add-MsolRoleMember
{
    # Mock stub for Add-MsolRoleMember
}

function Add-MsolScopedRoleMember
{
    # Mock stub for Add-MsolScopedRoleMember
}

function Confirm-MsolDomain
{
    # Mock stub for Confirm-MsolDomain
}

function Confirm-MsolEmailVerifiedDomain
{
    # Mock stub for Confirm-MsolEmailVerifiedDomain
}

function Connect-MsolService
{
    # Mock stub for Connect-MsolService
}

function Convert-MsolDomainToFederated
{
    # Mock stub for Convert-MsolDomainToFederated
}

function Convert-MsolDomainToStandard
{
    # Mock stub for Convert-MsolDomainToStandard
}

function Convert-MsolFederatedUser
{
    # Mock stub for Convert-MsolFederatedUser
}

function Disable-MsolDevice
{
    # Mock stub for Disable-MsolDevice
}

function Enable-MsolDevice
{
    # Mock stub for Enable-MsolDevice
}

function Get-MsolAccountSku
{
    # Mock stub for Get-MsolAccountSku
}

function Get-MsolAdministrativeUnit
{
    # Mock stub for Get-MsolAdministrativeUnit
}

function Get-MsolAdministrativeUnitMember
{
    # Mock stub for Get-MsolAdministrativeUnitMember
}

function Get-MsolCompanyAllowedDataLocation
{
    # Mock stub for Get-MsolCompanyAllowedDataLocation
}

function Get-MsolCompanyInformation
{
    # Mock stub for Get-MsolCompanyInformation
}

function Get-MsolContact
{
    # Mock stub for Get-MsolContact
}

function Get-MsolDevice
{
    # Mock stub for Get-MsolDevice
}

function Get-MsolDeviceRegistrationServicePolicy
{
    # Mock stub for Get-MsolDeviceRegistrationServicePolicy
}

function Get-MsolDirSyncConfiguration
{
    # Mock stub for Get-MsolDirSyncConfiguration
}

function Get-MsolDirSyncFeatures
{
    # Mock stub for Get-MsolDirSyncFeatures
}

function Get-MsolDirSyncProvisioningError
{
    # Mock stub for Get-MsolDirSyncProvisioningError
}

function Get-MsolDomain
{
    # Mock stub for Get-MsolDomain
}

function Get-MsolDomainFederationSettings
{
    # Mock stub for Get-MsolDomainFederationSettings
}

function Get-MsolDomainVerificationDns
{
    # Mock stub for Get-MsolDomainVerificationDns
}

function Get-MsolFederationProperty
{
    # Mock stub for Get-MsolFederationProperty
}

function Get-MsolGroup
{
    # Mock stub for Get-MsolGroup
}

function Get-MsolGroupMember
{
    # Mock stub for Get-MsolGroupMember
}

function Get-MsolHasObjectsWithDirSyncProvisioningErrors
{
    # Mock stub for Get-MsolHasObjectsWithDirSyncProvisioningErrors
}

function Get-MsolPartnerContract
{
    # Mock stub for Get-MsolPartnerContract
}

function Get-MsolPartnerInformation
{
    # Mock stub for Get-MsolPartnerInformation
}

function Get-MsolPasswordPolicy
{
    # Mock stub for Get-MsolPasswordPolicy
}

function Get-MsolRole
{
    # Mock stub for Get-MsolRole
}

function Get-MsolRoleMember
{
    # Mock stub for Get-MsolRoleMember
}

function Get-MsolScopedRoleMember
{
    # Mock stub for Get-MsolScopedRoleMember
}

function Get-MsolServicePrincipal
{
    # Mock stub for Get-MsolServicePrincipal
}

function Get-MsolServicePrincipalCredential
{
    # Mock stub for Get-MsolServicePrincipalCredential
}

function Get-MsolSubscription
{
    # Mock stub for Get-MsolSubscription
}

function Get-MsolUser
{
    # Mock stub for Get-MsolUser
}

function Get-MsolUserByStrongAuthentication
{
    # Mock stub for Get-MsolUserByStrongAuthentication
}

function Get-MsolUserRole
{
    # Mock stub for Get-MsolUserRole
}

function New-MsolAdministrativeUnit
{
    # Mock stub for New-MsolAdministrativeUnit
}

function New-MsolDomain
{
    # Mock stub for New-MsolDomain
}

function New-MsolFederatedDomain
{
    # Mock stub for New-MsolFederatedDomain
}

function New-MsolGroup
{
    # Mock stub for New-MsolGroup
}

function New-MsolLicenseOptions
{
    # Mock stub for New-MsolLicenseOptions
}

function New-MsolServicePrincipal
{
    # Mock stub for New-MsolServicePrincipal
}

function New-MsolServicePrincipalAddresses
{
    # Mock stub for New-MsolServicePrincipalAddresses
}

function New-MsolServicePrincipalCredential
{
    # Mock stub for New-MsolServicePrincipalCredential
}

function New-MsolUser
{
    # Mock stub for New-MsolUser
}

function New-MsolWellKnownGroup
{
    # Mock stub for New-MsolWellKnownGroup
}

function Redo-MsolProvisionContact
{
    # Mock stub for Redo-MsolProvisionContact
}

function Redo-MsolProvisionGroup
{
    # Mock stub for Redo-MsolProvisionGroup
}

function Redo-MsolProvisionUser
{
    # Mock stub for Redo-MsolProvisionUser
}

function Remove-MsolAdministrativeUnit
{
    # Mock stub for Remove-MsolAdministrativeUnit
}

function Remove-MsolAdministrativeUnitMember
{
    # Mock stub for Remove-MsolAdministrativeUnitMember
}

function Remove-MsolApplicationPassword
{
    # Mock stub for Remove-MsolApplicationPassword
}

function Remove-MsolContact
{
    # Mock stub for Remove-MsolContact
}

function Remove-MsolDevice
{
    # Mock stub for Remove-MsolDevice
}

function Remove-MsolDomain
{
    # Mock stub for Remove-MsolDomain
}

function Remove-MsolFederatedDomain
{
    # Mock stub for Remove-MsolFederatedDomain
}

function Remove-MsolForeignGroupFromRole
{
    # Mock stub for Remove-MsolForeignGroupFromRole
}

function Remove-MsolGroup
{
    # Mock stub for Remove-MsolGroup
}

function Remove-MsolGroupMember
{
    # Mock stub for Remove-MsolGroupMember
}

function Remove-MsolRoleMember
{
    # Mock stub for Remove-MsolRoleMember
}

function Remove-MsolScopedRoleMember
{
    # Mock stub for Remove-MsolScopedRoleMember
}

function Remove-MsolServicePrincipal
{
    # Mock stub for Remove-MsolServicePrincipal
}

function Remove-MsolServicePrincipalCredential
{
    # Mock stub for Remove-MsolServicePrincipalCredential
}

function Remove-MsolUser
{
    # Mock stub for Remove-MsolUser
}

function Reset-MsolStrongAuthenticationMethodByUpn
{
    # Mock stub for Reset-MsolStrongAuthenticationMethodByUpn
}

function Restore-MsolUser
{
    # Mock stub for Restore-MsolUser
}

function Set-MsolADFSContext
{
    # Mock stub for Set-MsolADFSContext
}

function Set-MsolAdministrativeUnit
{
    # Mock stub for Set-MsolAdministrativeUnit
}

function Set-MsolCompanyAllowedDataLocation
{
    # Mock stub for Set-MsolCompanyAllowedDataLocation
}

function Set-MsolCompanyContactInformation
{
    # Mock stub for Set-MsolCompanyContactInformation
}

function Set-MsolCompanyMultiNationalEnabled
{
    # Mock stub for Set-MsolCompanyMultiNationalEnabled
}

function Set-MsolCompanySecurityComplianceContactInformation
{
    # Mock stub for Set-MsolCompanySecurityComplianceContactInformation
}

function Set-MsolCompanySettings
{
    # Mock stub for Set-MsolCompanySettings
}

function Set-MsolDeviceRegistrationServicePolicy
{
    # Mock stub for Set-MsolDeviceRegistrationServicePolicy
}

function Set-MsolDirSyncConfiguration
{
    # Mock stub for Set-MsolDirSyncConfiguration
}

function Set-MsolDirSyncEnabled
{
    # Mock stub for Set-MsolDirSyncEnabled
}

function Set-MsolDirSyncFeature
{
    # Mock stub for Set-MsolDirSyncFeature
}

function Set-MsolDomain
{
    # Mock stub for Set-MsolDomain
}

function Set-MsolDomainAuthentication
{
    # Mock stub for Set-MsolDomainAuthentication
}

function Set-MsolDomainFederationSettings
{
    # Mock stub for Set-MsolDomainFederationSettings
}

function Set-MsolGroup
{
    # Mock stub for Set-MsolGroup
}

function Set-MsolPartnerInformation
{
    # Mock stub for Set-MsolPartnerInformation
}

function Set-MsolPasswordPolicy
{
    # Mock stub for Set-MsolPasswordPolicy
}

function Set-MsolServicePrincipal
{
    # Mock stub for Set-MsolServicePrincipal
}

function Set-MsolUser
{
    # Mock stub for Set-MsolUser
}

function Set-MsolUserLicense
{
    # Mock stub for Set-MsolUserLicense
}

function Set-MsolUserPassword
{
    # Mock stub for Set-MsolUserPassword
}

function Set-MsolUserPrincipalName
{
    # Mock stub for Set-MsolUserPrincipalName
}

function Update-MsolFederatedDomain
{
    # Mock stub for Update-MsolFederatedDomain
}

