# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: What kind of build is it?
  inputs:
    targetType: 'inline'
    script: |
      $alias = $env:BUILD_REQUESTEDFOREMAIL.Split('@')[0]
      $buildPrefix = '{0}_{1}' -f $alias, $env:BUILD_SOURCEBRANCHNAME
      $buildProduct = 'SfBServer'
      Write-Host "##vso[task.setvariable variable=BUILD_PREFIX]$buildPrefix"
      Write-Host "##vso[task.setvariable variable=BUILD_PRODUCT]$buildProduct"
- task: PowerShell@2
  displayName: Display the build variables that are available
  inputs:
   targetType: 'inline'
   script: |
     Get-ChildItem env:
- task: PowerShell@2
  displayName: Display source tree
  inputs:
   targetType: 'inline'
   script: |
     Get-ChildItem -Recurse -Path $(Build.SourcesDirectory)
- task: PowerShell@2
  displayName: Stamp support ownership on all files
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/StampOwners.ps1'
    arguments: "-OwnerName 'On Premise Diagnostic for SfBServer Support' -OwnerEmail 'pop-sfbsupport@microsoft.com' -Product $env:BUILD_PRODUCT"
- task: PowerShell@2
  displayName: Stamp version
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/ApplyVersionToConsole.ps1'
- task: PowerShell@2
  displayName: Stamp application insight key
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/SetApplicationInsightKey.ps1'
    arguments: '-Stage Development'
- task: PowerShell@2
  displayName: Stamp the product/ruleset version
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/Set-ProductMode.ps1'
    arguments: '-Product $env:BUILD_PRODUCT'
- task: PowerShell@2
  displayName: Set the product title
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/Set-Title.ps1'
    arguments: '-Product $env:BUILD_PRODUCT'    
- task: PowerShell@2
  displayName: Set the GitHub repo
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/Set-GitHubRepo.ps1'
    arguments: '-Product $env:BUILD_PRODUCT'
- task: PowerShell@2
  displayName: Run Script Analyzer
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/Invoke-ScriptAnalyzer.ps1'
    arguments: '-SourceDirectory $(Build.SourcesDirectory) -Product $env:BUILD_PRODUCT'
- task: PowerShell@2
  displayName: Run the Pester tests (English)
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/Invoke-TestCases.ps1'
    arguments: "-SourceDirectory $(Build.SourcesDirectory) -Product $env:BUILD_PRODUCT -Languages 'English'"
