# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  displayName: Set the product here
  inputs:
    targetType: 'inline'
    script: |
      $buildProduct = "SfBServer"
- task: PowerShell@2
  displayName: What kind of build is it?
  inputs:
    targetType: 'inline'
    script: |
      $alias = $env:BUILD_REQUESTEDFOREMAIL.Split('@')[0]
      $buildPrefix = '{0}_{1}' -f $alias, $env:BUILD_SOURCEBRANCHNAME
      
      Write-Host "##vso[task.setvariable variable=BUILD_PREFIX]$buildPrefix"
      Write-Host "##vso[task.setvariable variable=BUILD_PRODUCT]$buildProduct"
- task: PowerShell@2
  displayName: Display the build variables that are available
  inputs:
   targetType: 'inline'
   script: |
     Get-ChildItem env:
- task: PowerShell@2
  displayName: Stamp support ownership on all files
  inputs:
    filePath: '$(Build.SourcesDirectory)/buildhelpers/StampOwners.ps1'
    arguments: '-OwnerName ''On Premise Diagnostic for SfBServer Support'' -OwnerEmail ''pop-sfbsupport@microsoft.com'' -Product $env:BUILD_PRODUCT'
