#
# This file is autogenerated. Please do not edit directly
#
# Last generated by mmcintyr on 24/09/2020 2:36:06 PM
#

function Add-DatabaseAvailabilityGroupServer
{
    # Mock stub for Add-DatabaseAvailabilityGroupServer
}

function Add-MailboxDatabaseCopy
{
    # Mock stub for Add-MailboxDatabaseCopy
}

function Add-ResubmitRequest
{
    # Mock stub for Add-ResubmitRequest
}

function Add-ServerMonitoringOverride
{
    # Mock stub for Add-ServerMonitoringOverride
}

function Disable-MailboxQuarantine
{
    # Mock stub for Disable-MailboxQuarantine
}

function Disable-UMService
{
    # Mock stub for Disable-UMService
}

function Dismount-Database
{
    # Mock stub for Dismount-Database
}

function Dump-ProvisioningCache
{
    # Mock stub for Dump-ProvisioningCache
}

function Enable-ExchangeCertificate
{
    # Mock stub for Enable-ExchangeCertificate
}

function Enable-MailboxQuarantine
{
    # Mock stub for Enable-MailboxQuarantine
}

function Enable-UMService
{
    # Mock stub for Enable-UMService
}

function Export-ActiveSyncLog
{
    # Mock stub for Export-ActiveSyncLog
}

function Export-ExchangeCertificate
{
    # Mock stub for Export-ExchangeCertificate
}

function Export-Message
{
    # Mock stub for Export-Message
}

function Get-AcceptedDomain
{
    # Mock stub for Get-AcceptedDomain
}

function Get-ActiveSyncDeviceAutoblockThreshold
{
    # Mock stub for Get-ActiveSyncDeviceAutoblockThreshold
}

function Get-ActiveSyncVirtualDirectory
{
    # Mock stub for Get-ActiveSyncVirtualDirectory
}

function Get-ADServerSettings
{
    # Mock stub for Get-ADServerSettings
}

function Get-AutodiscoverVirtualDirectory
{
    # Mock stub for Get-AutodiscoverVirtualDirectory
}

function Get-ClientAccessServer
{
    # Mock stub for Get-ClientAccessServer
}

function Get-ClientAccessService
{
    # Mock stub for Get-ClientAccessService
}

function Get-ComplianceServiceVirtualDirectory
{
    # Mock stub for Get-ComplianceServiceVirtualDirectory
}

function Get-ContentFilterConfig
{
    # Mock stub for Get-ContentFilterConfig
}

function Get-DeliveryAgentConnector
{
    # Mock stub for Get-DeliveryAgentConnector
}

function Get-DomainController
{
    # Mock stub for Get-DomainController
}

function Get-EcpVirtualDirectory
{
    # Mock stub for Get-EcpVirtualDirectory
}

function Get-EventLogLevel
{
    # Mock stub for Get-EventLogLevel
}

function Get-ExchangeCertificate
{
    # Mock stub for Get-ExchangeCertificate
}

function Get-ExchangeServer
{
    # Mock stub for Get-ExchangeServer
}

function Get-ExchangeServerAccessLicense
{
    # Mock stub for Get-ExchangeServerAccessLicense
}

function Get-ExchangeServerAccessLicenseUser
{
    # Mock stub for Get-ExchangeServerAccessLicenseUser
}

function Get-FailedContentIndexDocuments
{
    # Mock stub for Get-FailedContentIndexDocuments
}

function Get-FrontendTransportService
{
    # Mock stub for Get-FrontendTransportService
}

function Get-ImapSettings
{
    # Mock stub for Get-ImapSettings
}

function Get-LogExportVirtualDirectory
{
    # Mock stub for Get-LogExportVirtualDirectory
}

function Get-Mailbox
{
    # Mock stub for Get-Mailbox
}

function Get-MailboxDatabase
{
    # Mock stub for Get-MailboxDatabase
}

function Get-MailboxDatabaseCopyStatus
{
    # Mock stub for Get-MailboxDatabaseCopyStatus
}

function Get-MailboxDatabaseRedundancy
{
    # Mock stub for Get-MailboxDatabaseRedundancy
}

function Get-MailboxDeliveryVirtualDirectory
{
    # Mock stub for Get-MailboxDeliveryVirtualDirectory
}

function Get-MailboxRepairRequest
{
    # Mock stub for Get-MailboxRepairRequest
}

function Get-MailboxServer
{
    # Mock stub for Get-MailboxServer
}

function Get-MailboxServerRedundancy
{
    # Mock stub for Get-MailboxServerRedundancy
}

function Get-MailboxSpellingConfiguration
{
    # Mock stub for Get-MailboxSpellingConfiguration
}

function Get-MailboxTransportService
{
    # Mock stub for Get-MailboxTransportService
}

function Get-MalwareFilteringServer
{
    # Mock stub for Get-MalwareFilteringServer
}

function Get-MapiVirtualDirectory
{
    # Mock stub for Get-MapiVirtualDirectory
}

function Get-Message
{
    # Mock stub for Get-Message
}

function Get-MonitoringItemHelp
{
    # Mock stub for Get-MonitoringItemHelp
}

function Get-MonitoringItemIdentity
{
    # Mock stub for Get-MonitoringItemIdentity
}

function Get-NetworkConnectionInfo
{
    # Mock stub for Get-NetworkConnectionInfo
}

function Get-Notification
{
    # Mock stub for Get-Notification
}

function Get-OabVirtualDirectory
{
    # Mock stub for Get-OabVirtualDirectory
}

function Get-OutlookAnywhere
{
    # Mock stub for Get-OutlookAnywhere
}

function Get-OutlookServiceVirtualDirectory
{
    # Mock stub for Get-OutlookServiceVirtualDirectory
}

function Get-OwaVirtualDirectory
{
    # Mock stub for Get-OwaVirtualDirectory
}

function Get-PopSettings
{
    # Mock stub for Get-PopSettings
}

function Get-PowerShellVirtualDirectory
{
    # Mock stub for Get-PowerShellVirtualDirectory
}

function Get-PublicFolderDatabase
{
    # Mock stub for Get-PublicFolderDatabase
}

function Get-Queue
{
    # Mock stub for Get-Queue
}

function Get-ReceiveConnector
{
    # Mock stub for Get-ReceiveConnector
}

function Get-Recipient
{
    # Mock stub for Get-Recipient
}

function Get-RestVirtualDirectory
{
    # Mock stub for Get-RestVirtualDirectory
}

function Get-ResubmitRequest
{
    # Mock stub for Get-ResubmitRequest
}

function Get-SearchDocumentFormat
{
    # Mock stub for Get-SearchDocumentFormat
}

function Get-ServerComponentState
{
    # Mock stub for Get-ServerComponentState
}

function Get-ServerMonitoringOverride
{
    # Mock stub for Get-ServerMonitoringOverride
}

function Get-StoreUsageStatistics
{
    # Mock stub for Get-StoreUsageStatistics
}

function Get-SubmissionMalwareFilteringServer
{
    # Mock stub for Get-SubmissionMalwareFilteringServer
}

function Get-TransportServer
{
    # Mock stub for Get-TransportServer
}

function Get-TransportService
{
    # Mock stub for Get-TransportService
}

function Get-UMCallRouterSettings
{
    # Mock stub for Get-UMCallRouterSettings
}

function Get-UMDialPlan
{
    # Mock stub for Get-UMDialPlan
}

function Get-UMIPGateway
{
    # Mock stub for Get-UMIPGateway
}

function Get-UMService
{
    # Mock stub for Get-UMService
}

function Get-UnifiedAuditSetting
{
    # Mock stub for Get-UnifiedAuditSetting
}

function Get-WebServicesVirtualDirectory
{
    # Mock stub for Get-WebServicesVirtualDirectory
}

function Import-ExchangeCertificate
{
    # Mock stub for Import-ExchangeCertificate
}

function Invoke-MonitoringProbe
{
    # Mock stub for Invoke-MonitoringProbe
}

function Mount-Database
{
    # Mock stub for Mount-Database
}

function Move-ActiveMailboxDatabase
{
    # Mock stub for Move-ActiveMailboxDatabase
}

function Move-DatabasePath
{
    # Mock stub for Move-DatabasePath
}

function New-ActiveSyncVirtualDirectory
{
    # Mock stub for New-ActiveSyncVirtualDirectory
}

function New-AutodiscoverVirtualDirectory
{
    # Mock stub for New-AutodiscoverVirtualDirectory
}

function New-ComplianceServiceVirtualDirectory
{
    # Mock stub for New-ComplianceServiceVirtualDirectory
}

function New-DeliveryAgentConnector
{
    # Mock stub for New-DeliveryAgentConnector
}

function New-EcpVirtualDirectory
{
    # Mock stub for New-EcpVirtualDirectory
}

function New-ExchangeCertificate
{
    # Mock stub for New-ExchangeCertificate
}

function New-MailboxDatabase
{
    # Mock stub for New-MailboxDatabase
}

function New-MailboxDeliveryVirtualDirectory
{
    # Mock stub for New-MailboxDeliveryVirtualDirectory
}

function New-MailboxRepairRequest
{
    # Mock stub for New-MailboxRepairRequest
}

function New-MapiVirtualDirectory
{
    # Mock stub for New-MapiVirtualDirectory
}

function New-OabVirtualDirectory
{
    # Mock stub for New-OabVirtualDirectory
}

function New-OutlookServiceVirtualDirectory
{
    # Mock stub for New-OutlookServiceVirtualDirectory
}

function New-OwaVirtualDirectory
{
    # Mock stub for New-OwaVirtualDirectory
}

function New-PowerShellVirtualDirectory
{
    # Mock stub for New-PowerShellVirtualDirectory
}

function New-ReceiveConnector
{
    # Mock stub for New-ReceiveConnector
}

function New-RestVirtualDirectory
{
    # Mock stub for New-RestVirtualDirectory
}

function New-SearchDocumentFormat
{
    # Mock stub for New-SearchDocumentFormat
}

function New-WebServicesVirtualDirectory
{
    # Mock stub for New-WebServicesVirtualDirectory
}

function Redirect-Message
{
    # Mock stub for Redirect-Message
}

function Remove-ActiveSyncVirtualDirectory
{
    # Mock stub for Remove-ActiveSyncVirtualDirectory
}

function Remove-AutodiscoverVirtualDirectory
{
    # Mock stub for Remove-AutodiscoverVirtualDirectory
}

function Remove-ComplianceServiceVirtualDirectory
{
    # Mock stub for Remove-ComplianceServiceVirtualDirectory
}

function Remove-ContentFilterPhrase
{
    # Mock stub for Remove-ContentFilterPhrase
}

function Remove-DatabaseAvailabilityGroupServer
{
    # Mock stub for Remove-DatabaseAvailabilityGroupServer
}

function Remove-DeliveryAgentConnector
{
    # Mock stub for Remove-DeliveryAgentConnector
}

function Remove-EcpVirtualDirectory
{
    # Mock stub for Remove-EcpVirtualDirectory
}

function Remove-ExchangeCertificate
{
    # Mock stub for Remove-ExchangeCertificate
}

function Remove-HybridConfiguration
{
    # Mock stub for Remove-HybridConfiguration
}

function Remove-MailboxDatabase
{
    # Mock stub for Remove-MailboxDatabase
}

function Remove-MailboxDatabaseCopy
{
    # Mock stub for Remove-MailboxDatabaseCopy
}

function Remove-MailboxDeliveryVirtualDirectory
{
    # Mock stub for Remove-MailboxDeliveryVirtualDirectory
}

function Remove-MailboxRepairRequest
{
    # Mock stub for Remove-MailboxRepairRequest
}

function Remove-MapiVirtualDirectory
{
    # Mock stub for Remove-MapiVirtualDirectory
}

function Remove-Message
{
    # Mock stub for Remove-Message
}

function Remove-OabVirtualDirectory
{
    # Mock stub for Remove-OabVirtualDirectory
}

function Remove-OutlookServiceVirtualDirectory
{
    # Mock stub for Remove-OutlookServiceVirtualDirectory
}

function Remove-OwaVirtualDirectory
{
    # Mock stub for Remove-OwaVirtualDirectory
}

function Remove-PowerShellVirtualDirectory
{
    # Mock stub for Remove-PowerShellVirtualDirectory
}

function Remove-ReceiveConnector
{
    # Mock stub for Remove-ReceiveConnector
}

function Remove-RestVirtualDirectory
{
    # Mock stub for Remove-RestVirtualDirectory
}

function Remove-ResubmitRequest
{
    # Mock stub for Remove-ResubmitRequest
}

function Remove-SearchDocumentFormat
{
    # Mock stub for Remove-SearchDocumentFormat
}

function Remove-ServerMonitoringOverride
{
    # Mock stub for Remove-ServerMonitoringOverride
}

function Remove-StoreMailbox
{
    # Mock stub for Remove-StoreMailbox
}

function Remove-UMMailboxPolicy
{
    # Mock stub for Remove-UMMailboxPolicy
}

function Remove-WebServicesVirtualDirectory
{
    # Mock stub for Remove-WebServicesVirtualDirectory
}

function Reset-ProvisioningCache
{
    # Mock stub for Reset-ProvisioningCache
}

function Resume-MailboxDatabaseCopy
{
    # Mock stub for Resume-MailboxDatabaseCopy
}

function Resume-Message
{
    # Mock stub for Resume-Message
}

function Resume-Queue
{
    # Mock stub for Resume-Queue
}

function Retry-Queue
{
    # Mock stub for Retry-Queue
}

function Set-ActiveSyncDeviceAutoblockThreshold
{
    # Mock stub for Set-ActiveSyncDeviceAutoblockThreshold
}

function Set-ActiveSyncVirtualDirectory
{
    # Mock stub for Set-ActiveSyncVirtualDirectory
}

function Set-ADServerSettings
{
    # Mock stub for Set-ADServerSettings
}

function Set-AutodiscoverVirtualDirectory
{
    # Mock stub for Set-AutodiscoverVirtualDirectory
}

function Set-CASMailbox
{
    # Mock stub for Set-CASMailbox
}

function Set-ClientAccessServer
{
    # Mock stub for Set-ClientAccessServer
}

function Set-ClientAccessService
{
    # Mock stub for Set-ClientAccessService
}

function Set-ComplianceServiceVirtualDirectory
{
    # Mock stub for Set-ComplianceServiceVirtualDirectory
}

function Set-ContentFilterConfig
{
    # Mock stub for Set-ContentFilterConfig
}

function Set-DeliveryAgentConnector
{
    # Mock stub for Set-DeliveryAgentConnector
}

function Set-EcpVirtualDirectory
{
    # Mock stub for Set-EcpVirtualDirectory
}

function Set-EventLogLevel
{
    # Mock stub for Set-EventLogLevel
}

function Set-ExchangeServer
{
    # Mock stub for Set-ExchangeServer
}

function Set-FrontendTransportService
{
    # Mock stub for Set-FrontendTransportService
}

function Set-ImapSettings
{
    # Mock stub for Set-ImapSettings
}

function Set-LogExportVirtualDirectory
{
    # Mock stub for Set-LogExportVirtualDirectory
}

function Set-MailboxDatabase
{
    # Mock stub for Set-MailboxDatabase
}

function Set-MailboxDatabaseCopy
{
    # Mock stub for Set-MailboxDatabaseCopy
}

function Set-MailboxDeliveryVirtualDirectory
{
    # Mock stub for Set-MailboxDeliveryVirtualDirectory
}

function Set-MailboxServer
{
    # Mock stub for Set-MailboxServer
}

function Set-MailboxTransportService
{
    # Mock stub for Set-MailboxTransportService
}

function Set-MalwareFilteringServer
{
    # Mock stub for Set-MalwareFilteringServer
}

function Set-MapiVirtualDirectory
{
    # Mock stub for Set-MapiVirtualDirectory
}

function Set-Notification
{
    # Mock stub for Set-Notification
}

function Set-OabVirtualDirectory
{
    # Mock stub for Set-OabVirtualDirectory
}

function Set-OutlookAnywhere
{
    # Mock stub for Set-OutlookAnywhere
}

function Set-OutlookServiceVirtualDirectory
{
    # Mock stub for Set-OutlookServiceVirtualDirectory
}

function Set-OwaVirtualDirectory
{
    # Mock stub for Set-OwaVirtualDirectory
}

function Set-PopSettings
{
    # Mock stub for Set-PopSettings
}

function Set-PowerShellVirtualDirectory
{
    # Mock stub for Set-PowerShellVirtualDirectory
}

function Set-ReceiveConnector
{
    # Mock stub for Set-ReceiveConnector
}

function Set-RestVirtualDirectory
{
    # Mock stub for Set-RestVirtualDirectory
}

function Set-ResubmitRequest
{
    # Mock stub for Set-ResubmitRequest
}

function Set-SearchDocumentFormat
{
    # Mock stub for Set-SearchDocumentFormat
}

function Set-ServerComponentState
{
    # Mock stub for Set-ServerComponentState
}

function Set-ServerMonitor
{
    # Mock stub for Set-ServerMonitor
}

function Set-SubmissionMalwareFilteringServer
{
    # Mock stub for Set-SubmissionMalwareFilteringServer
}

function Set-TransportServer
{
    # Mock stub for Set-TransportServer
}

function Set-TransportService
{
    # Mock stub for Set-TransportService
}

function Set-UMCallRouterSettings
{
    # Mock stub for Set-UMCallRouterSettings
}

function Set-UMService
{
    # Mock stub for Set-UMService
}

function Set-UnifiedAuditSetting
{
    # Mock stub for Set-UnifiedAuditSetting
}

function Set-WebServicesVirtualDirectory
{
    # Mock stub for Set-WebServicesVirtualDirectory
}

function Start-AuditAssistant
{
    # Mock stub for Start-AuditAssistant
}

function Suspend-MailboxDatabaseCopy
{
    # Mock stub for Suspend-MailboxDatabaseCopy
}

function Suspend-Message
{
    # Mock stub for Suspend-Message
}

function Suspend-Queue
{
    # Mock stub for Suspend-Queue
}

function Test-ActiveSyncConnectivity
{
    # Mock stub for Test-ActiveSyncConnectivity
}

function Test-ArchiveConnectivity
{
    # Mock stub for Test-ArchiveConnectivity
}

function Test-AssistantHealth
{
    # Mock stub for Test-AssistantHealth
}

function Test-CalendarConnectivity
{
    # Mock stub for Test-CalendarConnectivity
}

function Test-EcpConnectivity
{
    # Mock stub for Test-EcpConnectivity
}

function Test-EdgeSynchronization
{
    # Mock stub for Test-EdgeSynchronization
}

function Test-ExchangeSearch
{
    # Mock stub for Test-ExchangeSearch
}

function Test-FederationTrust
{
    # Mock stub for Test-FederationTrust
}

function Test-ImapConnectivity
{
    # Mock stub for Test-ImapConnectivity
}

function Test-IPAllowListProvider
{
    # Mock stub for Test-IPAllowListProvider
}

function Test-IPBlockListProvider
{
    # Mock stub for Test-IPBlockListProvider
}

function Test-IRMConfiguration
{
    # Mock stub for Test-IRMConfiguration
}

function Test-Mailflow
{
    # Mock stub for Test-Mailflow
}

function Test-MAPIConnectivity
{
    # Mock stub for Test-MAPIConnectivity
}

function Test-MLBHealth
{
    # Mock stub for Test-MLBHealth
}

function Test-MRSHealth
{
    # Mock stub for Test-MRSHealth
}

function Test-OAuthConnectivity
{
    # Mock stub for Test-OAuthConnectivity
}

function Test-OrganizationRelationship
{
    # Mock stub for Test-OrganizationRelationship
}

function Test-OutlookConnectivity
{
    # Mock stub for Test-OutlookConnectivity
}

function Test-OutlookWebServices
{
    # Mock stub for Test-OutlookWebServices
}

function Test-PopConnectivity
{
    # Mock stub for Test-PopConnectivity
}

function Test-PowerShellConnectivity
{
    # Mock stub for Test-PowerShellConnectivity
}

function Test-ReplicationHealth
{
    # Mock stub for Test-ReplicationHealth
}

function Test-SenderId
{
    # Mock stub for Test-SenderId
}

function Test-ServiceHealth
{
    # Mock stub for Test-ServiceHealth
}

function Test-SiteMailbox
{
    # Mock stub for Test-SiteMailbox
}

function Test-SmtpConnectivity
{
    # Mock stub for Test-SmtpConnectivity
}

function Test-UMConnectivity
{
    # Mock stub for Test-UMConnectivity
}

function Test-WebServicesConnectivity
{
    # Mock stub for Test-WebServicesConnectivity
}

function Update-DatabaseSchema
{
    # Mock stub for Update-DatabaseSchema
}

function Update-ExchangeHelp
{
    # Mock stub for Update-ExchangeHelp
}

function Update-HybridConfiguration
{
    # Mock stub for Update-HybridConfiguration
}

function Update-MailboxDatabaseCopy
{
    # Mock stub for Update-MailboxDatabaseCopy
}

function Update-OfflineAddressBook
{
    # Mock stub for Update-OfflineAddressBook
}

function Update-StoreMailboxState
{
    # Mock stub for Update-StoreMailboxState
}

function Write-AdminAuditLog
{
    # Mock stub for Write-AdminAuditLog
}

