#
# This file is autogenerated. Please do not edit directly
#
# Last generated by mmcintyr on 7/14/2021 8:42:46 PM
#

function Add-TeamUser
{
    # Mock stub for Add-TeamUser
}

function Clear-CsOnlineTelephoneNumberReservation
{
    # Mock stub for Clear-CsOnlineTelephoneNumberReservation
}

function Connect-MicrosoftTeams
{
    # Mock stub for Connect-MicrosoftTeams
}

function ConvertTo-JsonForPSWS
{
    # Mock stub for ConvertTo-JsonForPSWS
}

function Disable-CsMeetingRoom
{
    # Mock stub for Disable-CsMeetingRoom
}

function Disable-CsOnlineDialInConferencingUser
{
    # Mock stub for Disable-CsOnlineDialInConferencingUser
}

function Disable-CsOnlineSipDomain
{
    # Mock stub for Disable-CsOnlineSipDomain
}

function Disconnect-MicrosoftTeams
{
    # Mock stub for Disconnect-MicrosoftTeams
}

function Enable-CsMeetingRoom
{
    # Mock stub for Enable-CsMeetingRoom
}

function Enable-CsOnlineDialInConferencingUser
{
    # Mock stub for Enable-CsOnlineDialInConferencingUser
}

function Enable-CsOnlineSipDomain
{
    # Mock stub for Enable-CsOnlineSipDomain
}

function Export-CsAutoAttendantHolidays
{
    # Mock stub for Export-CsAutoAttendantHolidays
}

function Export-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Export-CsOrganizationalAutoAttendantHolidays
}

function Find-CsGroup
{
    # Mock stub for Find-CsGroup
}

function Find-CsOnlineApplicationInstance
{
    # Mock stub for Find-CsOnlineApplicationInstance
}

function Get-CsApplicationAccessPolicy
{
    # Mock stub for Get-CsApplicationAccessPolicy
}

function Get-CsApplicationMeetingConfiguration
{
    # Mock stub for Get-CsApplicationMeetingConfiguration
}

function Get-CsAudioConferencingProvider
{
    # Mock stub for Get-CsAudioConferencingProvider
}

function Get-CsAutoAttendant
{
    # Mock stub for Get-CsAutoAttendant
}

function Get-CsAutoAttendantHolidays
{
    # Mock stub for Get-CsAutoAttendantHolidays
}

function Get-CsAutoAttendantStatus
{
    # Mock stub for Get-CsAutoAttendantStatus
}

function Get-CsAutoAttendantSupportedLanguage
{
    # Mock stub for Get-CsAutoAttendantSupportedLanguage
}

function Get-CsAutoAttendantSupportedTimeZone
{
    # Mock stub for Get-CsAutoAttendantSupportedTimeZone
}

function Get-CsAutoAttendantTenantInformation
{
    # Mock stub for Get-CsAutoAttendantTenantInformation
}

function Get-CsBatchPolicyAssignmentOperation
{
    # Mock stub for Get-CsBatchPolicyAssignmentOperation
}

function Get-CsBroadcastMeetingConfiguration
{
    # Mock stub for Get-CsBroadcastMeetingConfiguration
}

function Get-CsBroadcastMeetingPolicy
{
    # Mock stub for Get-CsBroadcastMeetingPolicy
}

function Get-CsCallingLineIdentity
{
    # Mock stub for Get-CsCallingLineIdentity
}

function Get-CsCallQueue
{
    # Mock stub for Get-CsCallQueue
}

function Get-CsClientPolicy
{
    # Mock stub for Get-CsClientPolicy
}

function Get-CsCloudCallDataConnection
{
    # Mock stub for Get-CsCloudCallDataConnection
}

function Get-CsCloudMeetingPolicy
{
    # Mock stub for Get-CsCloudMeetingPolicy
}

function Get-CsConferencingPolicy
{
    # Mock stub for Get-CsConferencingPolicy
}

function Get-CsDefaultCatalogApp
{
    # Mock stub for Get-CsDefaultCatalogApp
}

function Get-CsDialPlan
{
    # Mock stub for Get-CsDialPlan
}

function Get-CsEffectiveTenantDialPlan
{
    # Mock stub for Get-CsEffectiveTenantDialPlan
}

function Get-CsExternalAccessPolicy
{
    # Mock stub for Get-CsExternalAccessPolicy
}

function Get-CsExternalUserCommunicationPolicy
{
    # Mock stub for Get-CsExternalUserCommunicationPolicy
}

function Get-CsGlobalCatalogApp
{
    # Mock stub for Get-CsGlobalCatalogApp
}

function Get-CsGraphPolicy
{
    # Mock stub for Get-CsGraphPolicy
}

function Get-CsGroupPolicyAssignment
{
    # Mock stub for Get-CsGroupPolicyAssignment
}

function Get-CsHostedVoicemailPolicy
{
    # Mock stub for Get-CsHostedVoicemailPolicy
}

function Get-CsHostingProvider
{
    # Mock stub for Get-CsHostingProvider
}

function Get-CsHuntGroup
{
    # Mock stub for Get-CsHuntGroup
}

function Get-CsHuntGroupTenantInformation
{
    # Mock stub for Get-CsHuntGroupTenantInformation
}

function Get-CsHybridMediationServer
{
    # Mock stub for Get-CsHybridMediationServer
}

function Get-CsHybridPSTNAppliance
{
    # Mock stub for Get-CsHybridPSTNAppliance
}

function Get-CsHybridPSTNSite
{
    # Mock stub for Get-CsHybridPSTNSite
}

function Get-CsImFilterConfiguration
{
    # Mock stub for Get-CsImFilterConfiguration
}

function Get-CsInboundBlockedNumberPattern
{
    # Mock stub for Get-CsInboundBlockedNumberPattern
}

function Get-CsInboundExemptNumberPattern
{
    # Mock stub for Get-CsInboundExemptNumberPattern
}

function Get-CsIPPhonePolicy
{
    # Mock stub for Get-CsIPPhonePolicy
}

function Get-CsMeetingConfiguration
{
    # Mock stub for Get-CsMeetingConfiguration
}

function Get-CsMeetingMigrationStatus
{
    # Mock stub for Get-CsMeetingMigrationStatus
}

function Get-CsMeetingRoom
{
    # Mock stub for Get-CsMeetingRoom
}

function Get-CsMobilityPolicy
{
    # Mock stub for Get-CsMobilityPolicy
}

function Get-CsNetworkConfiguration
{
    # Mock stub for Get-CsNetworkConfiguration
}

function Get-CsOAuthConfiguration
{
    # Mock stub for Get-CsOAuthConfiguration
}

function Get-CsOnlineApplicationEndpoint
{
    # Mock stub for Get-CsOnlineApplicationEndpoint
}

function Get-CsOnlineApplicationInstance
{
    # Mock stub for Get-CsOnlineApplicationInstance
}

function Get-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for Get-CsOnlineApplicationInstanceAssociation
}

function Get-CsOnlineApplicationInstanceAssociationStatus
{
    # Mock stub for Get-CsOnlineApplicationInstanceAssociationStatus
}

function Get-CsOnlineAudioConferencingRoutingPolicy
{
    # Mock stub for Get-CsOnlineAudioConferencingRoutingPolicy
}

function Get-CsOnlineDialInConferencingBridge
{
    # Mock stub for Get-CsOnlineDialInConferencingBridge
}

function Get-CsOnlineDialInConferencingLanguagesSupported
{
    # Mock stub for Get-CsOnlineDialInConferencingLanguagesSupported
}

function Get-CsOnlineDialinConferencingPolicy
{
    # Mock stub for Get-CsOnlineDialinConferencingPolicy
}

function Get-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Get-CsOnlineDialInConferencingServiceNumber
}

function Get-CsOnlineDialinConferencingTenantConfiguration
{
    # Mock stub for Get-CsOnlineDialinConferencingTenantConfiguration
}

function Get-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Get-CsOnlineDialInConferencingTenantSettings
}

function Get-CsOnlineDialInConferencingUser
{
    # Mock stub for Get-CsOnlineDialInConferencingUser
}

function Get-CsOnlineDialInConferencingUserInfo
{
    # Mock stub for Get-CsOnlineDialInConferencingUserInfo
}

function Get-CsOnlineDialInConferencingUserState
{
    # Mock stub for Get-CsOnlineDialInConferencingUserState
}

function Get-CsOnlineDialOutPolicy
{
    # Mock stub for Get-CsOnlineDialOutPolicy
}

function Get-CsOnlineDirectoryTenant
{
    # Mock stub for Get-CsOnlineDirectoryTenant
}

function Get-CsOnlineDirectoryTenantNumberCities
{
    # Mock stub for Get-CsOnlineDirectoryTenantNumberCities
}

function Get-CsOnlineEnhancedEmergencyServiceDisclaimer
{
    # Mock stub for Get-CsOnlineEnhancedEmergencyServiceDisclaimer
}

function Get-CsOnlineLisCivicAddress
{
    # Mock stub for Get-CsOnlineLisCivicAddress
}

function Get-CsOnlineLisLocation
{
    # Mock stub for Get-CsOnlineLisLocation
}

function Get-CsOnlineLisPort
{
    # Mock stub for Get-CsOnlineLisPort
}

function Get-CsOnlineLisSubnet
{
    # Mock stub for Get-CsOnlineLisSubnet
}

function Get-CsOnlineLisSwitch
{
    # Mock stub for Get-CsOnlineLisSwitch
}

function Get-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Get-CsOnlineLisWirelessAccessPoint
}

function Get-CsOnlineNumberPortInOrder
{
    # Mock stub for Get-CsOnlineNumberPortInOrder
}

function Get-CsOnlineNumberPortOutOrderPin
{
    # Mock stub for Get-CsOnlineNumberPortOutOrderPin
}

function Get-CsOnlinePowerShellEndpoint
{
    # Mock stub for Get-CsOnlinePowerShellEndpoint
}

function Get-CsOnlinePSTNGateway
{
    # Mock stub for Get-CsOnlinePSTNGateway
}

function Get-CsOnlinePstnUsage
{
    # Mock stub for Get-CsOnlinePstnUsage
}

function Get-CsOnlineSchedule
{
    # Mock stub for Get-CsOnlineSchedule
}

function Get-CsOnlineSipDomain
{
    # Mock stub for Get-CsOnlineSipDomain
}

function Get-CsOnlineTelephoneNumber
{
    # Mock stub for Get-CsOnlineTelephoneNumber
}

function Get-CsOnlineTelephoneNumberAvailableCount
{
    # Mock stub for Get-CsOnlineTelephoneNumberAvailableCount
}

function Get-CsOnlineTelephoneNumberInventoryAreas
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryAreas
}

function Get-CsOnlineTelephoneNumberInventoryCities
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryCities
}

function Get-CsOnlineTelephoneNumberInventoryCountries
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryCountries
}

function Get-CsOnlineTelephoneNumberInventoryRegions
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryRegions
}

function Get-CsOnlineTelephoneNumberInventoryTypes
{
    # Mock stub for Get-CsOnlineTelephoneNumberInventoryTypes
}

function Get-CsOnlineTelephoneNumberReservationsInformation
{
    # Mock stub for Get-CsOnlineTelephoneNumberReservationsInformation
}

function Get-CsOnlineUser
{
    # Mock stub for Get-CsOnlineUser
}

function Get-CsOnlineVoicemailPolicy
{
    # Mock stub for Get-CsOnlineVoicemailPolicy
}

function Get-CsOnlineVoicemailUserSettings
{
    # Mock stub for Get-CsOnlineVoicemailUserSettings
}

function Get-CsOnlineVoiceRoute
{
    # Mock stub for Get-CsOnlineVoiceRoute
}

function Get-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Get-CsOnlineVoiceRoutingPolicy
}

function Get-CsOnlineVoiceUser
{
    # Mock stub for Get-CsOnlineVoiceUser
}

function Get-CsOrganizationalAutoAttendant
{
    # Mock stub for Get-CsOrganizationalAutoAttendant
}

function Get-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Get-CsOrganizationalAutoAttendantHolidays
}

function Get-CsOrganizationalAutoAttendantStatus
{
    # Mock stub for Get-CsOrganizationalAutoAttendantStatus
}

function Get-CsOrganizationalAutoAttendantSupportedLanguage
{
    # Mock stub for Get-CsOrganizationalAutoAttendantSupportedLanguage
}

function Get-CsOrganizationalAutoAttendantSupportedTimeZone
{
    # Mock stub for Get-CsOrganizationalAutoAttendantSupportedTimeZone
}

function Get-CsOrganizationalAutoAttendantTenantInformation
{
    # Mock stub for Get-CsOrganizationalAutoAttendantTenantInformation
}

function Get-CsPolicyPackage
{
    # Mock stub for Get-CsPolicyPackage
}

function Get-CsPresencePolicy
{
    # Mock stub for Get-CsPresencePolicy
}

function Get-CsPrivacyConfiguration
{
    # Mock stub for Get-CsPrivacyConfiguration
}

function Get-CsPushNotificationConfiguration
{
    # Mock stub for Get-CsPushNotificationConfiguration
}

function Get-CsTeamsAcsFederationConfiguration
{
    # Mock stub for Get-CsTeamsAcsFederationConfiguration
}

function Get-CsTeamsAppPermissionPolicy
{
    # Mock stub for Get-CsTeamsAppPermissionPolicy
}

function Get-CsTeamsAppPreset
{
    # Mock stub for Get-CsTeamsAppPreset
}

function Get-CsTeamsAppSetupPolicy
{
    # Mock stub for Get-CsTeamsAppSetupPolicy
}

function Get-CsTeamsCallHoldPolicy
{
    # Mock stub for Get-CsTeamsCallHoldPolicy
}

function Get-CsTeamsCallingPolicy
{
    # Mock stub for Get-CsTeamsCallingPolicy
}

function Get-CsTeamsCallParkPolicy
{
    # Mock stub for Get-CsTeamsCallParkPolicy
}

function Get-CsTeamsChannelsPolicy
{
    # Mock stub for Get-CsTeamsChannelsPolicy
}

function Get-CsTeamsClientConfiguration
{
    # Mock stub for Get-CsTeamsClientConfiguration
}

function Get-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Get-CsTeamsComplianceRecordingApplication
}

function Get-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Get-CsTeamsComplianceRecordingPolicy
}

function Get-CsTeamsCortanaPolicy
{
    # Mock stub for Get-CsTeamsCortanaPolicy
}

function Get-CsTeamsEducationAssignmentsAppPolicy
{
    # Mock stub for Get-CsTeamsEducationAssignmentsAppPolicy
}

function Get-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Get-CsTeamsEmergencyCallingPolicy
}

function Get-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Get-CsTeamsEmergencyCallRoutingPolicy
}

function Get-CsTeamsFeedbackPolicy
{
    # Mock stub for Get-CsTeamsFeedbackPolicy
}

function Get-CsTeamsGuestCallingConfiguration
{
    # Mock stub for Get-CsTeamsGuestCallingConfiguration
}

function Get-CsTeamsGuestMeetingConfiguration
{
    # Mock stub for Get-CsTeamsGuestMeetingConfiguration
}

function Get-CsTeamsGuestMessagingConfiguration
{
    # Mock stub for Get-CsTeamsGuestMessagingConfiguration
}

function Get-CsTeamsIPPhonePolicy
{
    # Mock stub for Get-CsTeamsIPPhonePolicy
}

function Get-CsTeamsMeetingBroadcastConfiguration
{
    # Mock stub for Get-CsTeamsMeetingBroadcastConfiguration
}

function Get-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Get-CsTeamsMeetingBroadcastPolicy
}

function Get-CsTeamsMeetingConfiguration
{
    # Mock stub for Get-CsTeamsMeetingConfiguration
}

function Get-CsTeamsMeetingPolicy
{
    # Mock stub for Get-CsTeamsMeetingPolicy
}

function Get-CsTeamsMessagingPolicy
{
    # Mock stub for Get-CsTeamsMessagingPolicy
}

function Get-CsTeamsMigrationConfiguration
{
    # Mock stub for Get-CsTeamsMigrationConfiguration
}

function Get-CsTeamsMobilityPolicy
{
    # Mock stub for Get-CsTeamsMobilityPolicy
}

function Get-CsTeamsNetworkRoamingPolicy
{
    # Mock stub for Get-CsTeamsNetworkRoamingPolicy
}

function Get-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Get-CsTeamsNotificationAndFeedsPolicy
}

function Get-CsTeamsPinnedApp
{
    # Mock stub for Get-CsTeamsPinnedApp
}

function Get-CsTeamsShiftsAppPolicy
{
    # Mock stub for Get-CsTeamsShiftsAppPolicy
}

function Get-CsTeamsShiftsPolicy
{
    # Mock stub for Get-CsTeamsShiftsPolicy
}

function Get-CsTeamsSurvivableBranchAppliance
{
    # Mock stub for Get-CsTeamsSurvivableBranchAppliance
}

function Get-CsTeamsSurvivableBranchAppliancePolicy
{
    # Mock stub for Get-CsTeamsSurvivableBranchAppliancePolicy
}

function Get-CsTeamsTargetingPolicy
{
    # Mock stub for Get-CsTeamsTargetingPolicy
}

function Get-CsTeamsTranslationRule
{
    # Mock stub for Get-CsTeamsTranslationRule
}

function Get-CsTeamsUpdateManagementPolicy
{
    # Mock stub for Get-CsTeamsUpdateManagementPolicy
}

function Get-CsTeamsUpgradeConfiguration
{
    # Mock stub for Get-CsTeamsUpgradeConfiguration
}

function Get-CsTeamsUpgradePolicy
{
    # Mock stub for Get-CsTeamsUpgradePolicy
}

function Get-CsTeamsUpgradeStatus
{
    # Mock stub for Get-CsTeamsUpgradeStatus
}

function Get-CsTeamsVdiPolicy
{
    # Mock stub for Get-CsTeamsVdiPolicy
}

function Get-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Get-CsTeamsVerticalPackagePolicy
}

function Get-CsTeamsVideoInteropServicePolicy
{
    # Mock stub for Get-CsTeamsVideoInteropServicePolicy
}

function Get-CsTeamsWorkLoadPolicy
{
    # Mock stub for Get-CsTeamsWorkLoadPolicy
}

function Get-CsTeamTemplate
{
    # Mock stub for Get-CsTeamTemplate
}

function Get-CsTeamTemplateList
{
    # Mock stub for Get-CsTeamTemplateList
}

function Get-CsTenant
{
    # Mock stub for Get-CsTenant
}

function Get-CsTenantBlockedCallingNumbers
{
    # Mock stub for Get-CsTenantBlockedCallingNumbers
}

function Get-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Get-CsTenantBlockedNumberExceptionPattern
}

function Get-CsTenantCatalogApp
{
    # Mock stub for Get-CsTenantCatalogApp
}

function Get-CsTenantDialPlan
{
    # Mock stub for Get-CsTenantDialPlan
}

function Get-CsTenantFederationConfiguration
{
    # Mock stub for Get-CsTenantFederationConfiguration
}

function Get-CsTenantHybridConfiguration
{
    # Mock stub for Get-CsTenantHybridConfiguration
}

function Get-CsTenantLicensingConfiguration
{
    # Mock stub for Get-CsTenantLicensingConfiguration
}

function Get-CsTenantMigrationConfiguration
{
    # Mock stub for Get-CsTenantMigrationConfiguration
}

function Get-CsTenantNetworkConfiguration
{
    # Mock stub for Get-CsTenantNetworkConfiguration
}

function Get-CsTenantNetworkPostalCode
{
    # Mock stub for Get-CsTenantNetworkPostalCode
}

function Get-CsTenantNetworkRegion
{
    # Mock stub for Get-CsTenantNetworkRegion
}

function Get-CsTenantNetworkSite
{
    # Mock stub for Get-CsTenantNetworkSite
}

function Get-CsTenantNetworkSubnet
{
    # Mock stub for Get-CsTenantNetworkSubnet
}

function Get-CsTenantPublicProvider
{
    # Mock stub for Get-CsTenantPublicProvider
}

function Get-CsTenantTrustedIPAddress
{
    # Mock stub for Get-CsTenantTrustedIPAddress
}

function Get-CsTenantUpdateTimeWindow
{
    # Mock stub for Get-CsTenantUpdateTimeWindow
}

function Get-CsUCPhoneConfiguration
{
    # Mock stub for Get-CsUCPhoneConfiguration
}

function Get-CsUserAcp
{
    # Mock stub for Get-CsUserAcp
}

function Get-CsUserLocationStatus
{
    # Mock stub for Get-CsUserLocationStatus
}

function Get-CsUserPolicyAssignment
{
    # Mock stub for Get-CsUserPolicyAssignment
}

function Get-CsUserPolicyPackage
{
    # Mock stub for Get-CsUserPolicyPackage
}

function Get-CsUserPolicyPackageRecommendation
{
    # Mock stub for Get-CsUserPolicyPackageRecommendation
}

function Get-CsUserPstnSettings
{
    # Mock stub for Get-CsUserPstnSettings
}

function Get-CsUserServicesPolicy
{
    # Mock stub for Get-CsUserServicesPolicy
}

function Get-CsVideoInteropServiceProvider
{
    # Mock stub for Get-CsVideoInteropServiceProvider
}

function Get-CsVoiceNormalizationRule
{
    # Mock stub for Get-CsVoiceNormalizationRule
}

function Get-CsVoiceRoutingPolicy
{
    # Mock stub for Get-CsVoiceRoutingPolicy
}

function Get-MultiGeoRegion
{
    # Mock stub for Get-MultiGeoRegion
}

function Get-Team
{
    # Mock stub for Get-Team
}

function Get-TeamChannel
{
    # Mock stub for Get-TeamChannel
}

function Get-TeamsApp
{
    # Mock stub for Get-TeamsApp
}

function Get-TeamUser
{
    # Mock stub for Get-TeamUser
}

function Grant-CsApplicationAccessPolicy
{
    # Mock stub for Grant-CsApplicationAccessPolicy
}

function Grant-CsBroadcastMeetingPolicy
{
    # Mock stub for Grant-CsBroadcastMeetingPolicy
}

function Grant-CsCallingLineIdentity
{
    # Mock stub for Grant-CsCallingLineIdentity
}

function Grant-CsClientPolicy
{
    # Mock stub for Grant-CsClientPolicy
}

function Grant-CsCloudMeetingPolicy
{
    # Mock stub for Grant-CsCloudMeetingPolicy
}

function Grant-CsConferencingPolicy
{
    # Mock stub for Grant-CsConferencingPolicy
}

function Grant-CsDialoutPolicy
{
    # Mock stub for Grant-CsDialoutPolicy
}

function Grant-CsExternalAccessPolicy
{
    # Mock stub for Grant-CsExternalAccessPolicy
}

function Grant-CsExternalUserCommunicationPolicy
{
    # Mock stub for Grant-CsExternalUserCommunicationPolicy
}

function Grant-CsGraphPolicy
{
    # Mock stub for Grant-CsGraphPolicy
}

function Grant-CsGroupPolicyPackageAssignment
{
    # Mock stub for Grant-CsGroupPolicyPackageAssignment
}

function Grant-CsHostedVoicemailPolicy
{
    # Mock stub for Grant-CsHostedVoicemailPolicy
}

function Grant-CsIPPhonePolicy
{
    # Mock stub for Grant-CsIPPhonePolicy
}

function Grant-CsMobilityPolicy
{
    # Mock stub for Grant-CsMobilityPolicy
}

function Grant-CsOnlineAudioConferencingRoutingPolicy
{
    # Mock stub for Grant-CsOnlineAudioConferencingRoutingPolicy
}

function Grant-CsOnlineVoicemailPolicy
{
    # Mock stub for Grant-CsOnlineVoicemailPolicy
}

function Grant-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Grant-CsOnlineVoiceRoutingPolicy
}

function Grant-CsPolicy
{
    # Mock stub for Grant-CsPolicy
}

function Grant-CsTeamsAppPermissionPolicy
{
    # Mock stub for Grant-CsTeamsAppPermissionPolicy
}

function Grant-CsTeamsAppSetupPolicy
{
    # Mock stub for Grant-CsTeamsAppSetupPolicy
}

function Grant-CsTeamsCallHoldPolicy
{
    # Mock stub for Grant-CsTeamsCallHoldPolicy
}

function Grant-CsTeamsCallingPolicy
{
    # Mock stub for Grant-CsTeamsCallingPolicy
}

function Grant-CsTeamsCallParkPolicy
{
    # Mock stub for Grant-CsTeamsCallParkPolicy
}

function Grant-CsTeamsChannelsPolicy
{
    # Mock stub for Grant-CsTeamsChannelsPolicy
}

function Grant-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Grant-CsTeamsComplianceRecordingPolicy
}

function Grant-CsTeamsCortanaPolicy
{
    # Mock stub for Grant-CsTeamsCortanaPolicy
}

function Grant-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Grant-CsTeamsEmergencyCallingPolicy
}

function Grant-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Grant-CsTeamsEmergencyCallRoutingPolicy
}

function Grant-CsTeamsFeedbackPolicy
{
    # Mock stub for Grant-CsTeamsFeedbackPolicy
}

function Grant-CsTeamsIPPhonePolicy
{
    # Mock stub for Grant-CsTeamsIPPhonePolicy
}

function Grant-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Grant-CsTeamsMeetingBroadcastPolicy
}

function Grant-CsTeamsMeetingPolicy
{
    # Mock stub for Grant-CsTeamsMeetingPolicy
}

function Grant-CsTeamsMessagingPolicy
{
    # Mock stub for Grant-CsTeamsMessagingPolicy
}

function Grant-CsTeamsMobilityPolicy
{
    # Mock stub for Grant-CsTeamsMobilityPolicy
}

function Grant-CsTeamsShiftsPolicy
{
    # Mock stub for Grant-CsTeamsShiftsPolicy
}

function Grant-CsTeamsSurvivableBranchAppliancePolicy
{
    # Mock stub for Grant-CsTeamsSurvivableBranchAppliancePolicy
}

function Grant-CsTeamsUpdateManagementPolicy
{
    # Mock stub for Grant-CsTeamsUpdateManagementPolicy
}

function Grant-CsTeamsUpgradePolicy
{
    # Mock stub for Grant-CsTeamsUpgradePolicy
}

function Grant-CsTeamsVdiPolicy
{
    # Mock stub for Grant-CsTeamsVdiPolicy
}

function Grant-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Grant-CsTeamsVerticalPackagePolicy
}

function Grant-CsTeamsVideoInteropServicePolicy
{
    # Mock stub for Grant-CsTeamsVideoInteropServicePolicy
}

function Grant-CsTeamsWorkLoadPolicy
{
    # Mock stub for Grant-CsTeamsWorkLoadPolicy
}

function Grant-CsTenantDialPlan
{
    # Mock stub for Grant-CsTenantDialPlan
}

function Grant-CsUserPolicyPackage
{
    # Mock stub for Grant-CsUserPolicyPackage
}

function Grant-CsVoiceRoutingPolicy
{
    # Mock stub for Grant-CsVoiceRoutingPolicy
}

function Import-CsAutoAttendantHolidays
{
    # Mock stub for Import-CsAutoAttendantHolidays
}

function Import-CsOnlineAudioFile
{
    # Mock stub for Import-CsOnlineAudioFile
}

function Import-CsOrganizationalAutoAttendantHolidays
{
    # Mock stub for Import-CsOrganizationalAutoAttendantHolidays
}

function Invoke-CsInternalPsTelemetry
{
    # Mock stub for Invoke-CsInternalPsTelemetry
}

function Invoke-CsUcsRollback
{
    # Mock stub for Invoke-CsUcsRollback
}

function Invoke-CsUserPreferredDataLocationSync
{
    # Mock stub for Invoke-CsUserPreferredDataLocationSync
}

function Move-CsInternalHelper
{
    # Mock stub for Move-CsInternalHelper
}

function New-CsApplicationAccessPolicy
{
    # Mock stub for New-CsApplicationAccessPolicy
}

function New-CsAutoAttendant
{
    # Mock stub for New-CsAutoAttendant
}

function New-CsAutoAttendantCallableEntity
{
    # Mock stub for New-CsAutoAttendantCallableEntity
}

function New-CsAutoAttendantCallFlow
{
    # Mock stub for New-CsAutoAttendantCallFlow
}

function New-CsAutoAttendantCallHandlingAssociation
{
    # Mock stub for New-CsAutoAttendantCallHandlingAssociation
}

function New-CsAutoAttendantDialScope
{
    # Mock stub for New-CsAutoAttendantDialScope
}

function New-CsAutoAttendantMenu
{
    # Mock stub for New-CsAutoAttendantMenu
}

function New-CsAutoAttendantMenuOption
{
    # Mock stub for New-CsAutoAttendantMenuOption
}

function New-CsAutoAttendantPrompt
{
    # Mock stub for New-CsAutoAttendantPrompt
}

function New-CsBatchPolicyAssignmentOperation
{
    # Mock stub for New-CsBatchPolicyAssignmentOperation
}

function New-CsBatchPolicyPackageAssignmentOperation
{
    # Mock stub for New-CsBatchPolicyPackageAssignmentOperation
}

function New-CsCallingLineIdentity
{
    # Mock stub for New-CsCallingLineIdentity
}

function New-CsCallQueue
{
    # Mock stub for New-CsCallQueue
}

function New-CsClientPolicy
{
    # Mock stub for New-CsClientPolicy
}

function New-CsCloudCallDataConnection
{
    # Mock stub for New-CsCloudCallDataConnection
}

function New-CsConferencingPolicy
{
    # Mock stub for New-CsConferencingPolicy
}

function New-CsCustomPolicyPackage
{
    # Mock stub for New-CsCustomPolicyPackage
}

function New-CsDefaultCatalogApp
{
    # Mock stub for New-CsDefaultCatalogApp
}

function New-CsEdgeAllowAllKnownDomains
{
    # Mock stub for New-CsEdgeAllowAllKnownDomains
}

function New-CsEdgeAllowList
{
    # Mock stub for New-CsEdgeAllowList
}

function New-CsEdgeDomainPattern
{
    # Mock stub for New-CsEdgeDomainPattern
}

function New-CsExternalAccessPolicy
{
    # Mock stub for New-CsExternalAccessPolicy
}

function New-CsExternalUserCommunicationPolicy
{
    # Mock stub for New-CsExternalUserCommunicationPolicy
}

function New-CsGlobalCatalogApp
{
    # Mock stub for New-CsGlobalCatalogApp
}

function New-CsGroupPolicyAssignment
{
    # Mock stub for New-CsGroupPolicyAssignment
}

function New-CsHuntGroup
{
    # Mock stub for New-CsHuntGroup
}

function New-CsHybridPSTNSite
{
    # Mock stub for New-CsHybridPSTNSite
}

function New-CsHybridTelephoneNumber
{
    # Mock stub for New-CsHybridTelephoneNumber
}

function New-CsInboundBlockedNumberPattern
{
    # Mock stub for New-CsInboundBlockedNumberPattern
}

function New-CsInboundExemptNumberPattern
{
    # Mock stub for New-CsInboundExemptNumberPattern
}

function New-CsMobilityPolicy
{
    # Mock stub for New-CsMobilityPolicy
}

function New-CsNetworkMediaBypassConfiguration
{
    # Mock stub for New-CsNetworkMediaBypassConfiguration
}

function New-CsOnlineApplicationEndpoint
{
    # Mock stub for New-CsOnlineApplicationEndpoint
}

function New-CsOnlineApplicationInstance
{
    # Mock stub for New-CsOnlineApplicationInstance
}

function New-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for New-CsOnlineApplicationInstanceAssociation
}

function New-CsOnlineAudioConferencingRoutingPolicy
{
    # Mock stub for New-CsOnlineAudioConferencingRoutingPolicy
}

function New-CsOnlineAudioFile
{
    # Mock stub for New-CsOnlineAudioFile
}

function New-CsOnlineBulkAssignmentInput
{
    # Mock stub for New-CsOnlineBulkAssignmentInput
}

function New-CsOnlineDateTimeRange
{
    # Mock stub for New-CsOnlineDateTimeRange
}

function New-CsOnlineLisCivicAddress
{
    # Mock stub for New-CsOnlineLisCivicAddress
}

function New-CsOnlineLisLocation
{
    # Mock stub for New-CsOnlineLisLocation
}

function New-CsOnlineNumberPortInOrder
{
    # Mock stub for New-CsOnlineNumberPortInOrder
}

function New-CsOnlinePSTNGateway
{
    # Mock stub for New-CsOnlinePSTNGateway
}

function New-CsOnlineSchedule
{
    # Mock stub for New-CsOnlineSchedule
}

function New-CsOnlineTimeRange
{
    # Mock stub for New-CsOnlineTimeRange
}

function New-CsOnlineVoicemailPolicy
{
    # Mock stub for New-CsOnlineVoicemailPolicy
}

function New-CsOnlineVoiceRoute
{
    # Mock stub for New-CsOnlineVoiceRoute
}

function New-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for New-CsOnlineVoiceRoutingPolicy
}

function New-CsOrganizationalAutoAttendant
{
    # Mock stub for New-CsOrganizationalAutoAttendant
}

function New-CsOrganizationalAutoAttendantCallableEntity
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallableEntity
}

function New-CsOrganizationalAutoAttendantCallFlow
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallFlow
}

function New-CsOrganizationalAutoAttendantCallHandlingAssociation
{
    # Mock stub for New-CsOrganizationalAutoAttendantCallHandlingAssociation
}

function New-CsOrganizationalAutoAttendantDialScope
{
    # Mock stub for New-CsOrganizationalAutoAttendantDialScope
}

function New-CsOrganizationalAutoAttendantMenu
{
    # Mock stub for New-CsOrganizationalAutoAttendantMenu
}

function New-CsOrganizationalAutoAttendantMenuOption
{
    # Mock stub for New-CsOrganizationalAutoAttendantMenuOption
}

function New-CsOrganizationalAutoAttendantPrompt
{
    # Mock stub for New-CsOrganizationalAutoAttendantPrompt
}

function New-CsTeamsAppPermissionPolicy
{
    # Mock stub for New-CsTeamsAppPermissionPolicy
}

function New-CsTeamsAppPreset
{
    # Mock stub for New-CsTeamsAppPreset
}

function New-CsTeamsAppSetupPolicy
{
    # Mock stub for New-CsTeamsAppSetupPolicy
}

function New-CsTeamsCallHoldPolicy
{
    # Mock stub for New-CsTeamsCallHoldPolicy
}

function New-CsTeamsCallingPolicy
{
    # Mock stub for New-CsTeamsCallingPolicy
}

function New-CsTeamsCallParkPolicy
{
    # Mock stub for New-CsTeamsCallParkPolicy
}

function New-CsTeamsChannelsPolicy
{
    # Mock stub for New-CsTeamsChannelsPolicy
}

function New-CsTeamsComplianceRecordingApplication
{
    # Mock stub for New-CsTeamsComplianceRecordingApplication
}

function New-CsTeamsComplianceRecordingPairedApplication
{
    # Mock stub for New-CsTeamsComplianceRecordingPairedApplication
}

function New-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for New-CsTeamsComplianceRecordingPolicy
}

function New-CsTeamsCortanaPolicy
{
    # Mock stub for New-CsTeamsCortanaPolicy
}

function New-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for New-CsTeamsEmergencyCallingPolicy
}

function New-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for New-CsTeamsEmergencyCallRoutingPolicy
}

function New-CsTeamsEmergencyNumber
{
    # Mock stub for New-CsTeamsEmergencyNumber
}

function New-CsTeamsFeedbackPolicy
{
    # Mock stub for New-CsTeamsFeedbackPolicy
}

function New-CsTeamsIPPhonePolicy
{
    # Mock stub for New-CsTeamsIPPhonePolicy
}

function New-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for New-CsTeamsMeetingBroadcastPolicy
}

function New-CsTeamsMeetingPolicy
{
    # Mock stub for New-CsTeamsMeetingPolicy
}

function New-CsTeamsMessagingPolicy
{
    # Mock stub for New-CsTeamsMessagingPolicy
}

function New-CsTeamsMobilityPolicy
{
    # Mock stub for New-CsTeamsMobilityPolicy
}

function New-CsTeamsNetworkRoamingPolicy
{
    # Mock stub for New-CsTeamsNetworkRoamingPolicy
}

function New-CsTeamsPinnedApp
{
    # Mock stub for New-CsTeamsPinnedApp
}

function New-CsTeamsShiftsPolicy
{
    # Mock stub for New-CsTeamsShiftsPolicy
}

function New-CsTeamsSurvivableBranchAppliance
{
    # Mock stub for New-CsTeamsSurvivableBranchAppliance
}

function New-CsTeamsSurvivableBranchAppliancePolicy
{
    # Mock stub for New-CsTeamsSurvivableBranchAppliancePolicy
}

function New-CsTeamsTranslationRule
{
    # Mock stub for New-CsTeamsTranslationRule
}

function New-CsTeamsUpdateManagementPolicy
{
    # Mock stub for New-CsTeamsUpdateManagementPolicy
}

function New-CsTeamsVdiPolicy
{
    # Mock stub for New-CsTeamsVdiPolicy
}

function New-CsTeamsVerticalPackagePolicy
{
    # Mock stub for New-CsTeamsVerticalPackagePolicy
}

function New-CsTeamsWorkLoadPolicy
{
    # Mock stub for New-CsTeamsWorkLoadPolicy
}

function New-CsTeamTemplate
{
    # Mock stub for New-CsTeamTemplate
}

function New-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for New-CsTenantBlockedNumberExceptionPattern
}

function New-CsTenantCatalogApp
{
    # Mock stub for New-CsTenantCatalogApp
}

function New-CsTenantDialPlan
{
    # Mock stub for New-CsTenantDialPlan
}

function New-CsTenantNetworkPostalCode
{
    # Mock stub for New-CsTenantNetworkPostalCode
}

function New-CsTenantNetworkRegion
{
    # Mock stub for New-CsTenantNetworkRegion
}

function New-CsTenantNetworkSite
{
    # Mock stub for New-CsTenantNetworkSite
}

function New-CsTenantNetworkSubnet
{
    # Mock stub for New-CsTenantNetworkSubnet
}

function New-CsTenantTrustedIPAddress
{
    # Mock stub for New-CsTenantTrustedIPAddress
}

function New-CsTenantUpdateTimeWindow
{
    # Mock stub for New-CsTenantUpdateTimeWindow
}

function New-CsVideoInteropServiceProvider
{
    # Mock stub for New-CsVideoInteropServiceProvider
}

function New-CsVoiceNormalizationRule
{
    # Mock stub for New-CsVoiceNormalizationRule
}

function New-Team
{
    # Mock stub for New-Team
}

function New-TeamChannel
{
    # Mock stub for New-TeamChannel
}

function New-TeamsApp
{
    # Mock stub for New-TeamsApp
}

function Register-CsHybridPSTNAppliance
{
    # Mock stub for Register-CsHybridPSTNAppliance
}

function Register-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Register-CsOnlineDialInConferencingServiceNumber
}

function Remove-CsApplicationAccessPolicy
{
    # Mock stub for Remove-CsApplicationAccessPolicy
}

function Remove-CsAutoAttendant
{
    # Mock stub for Remove-CsAutoAttendant
}

function Remove-CsCallingLineIdentity
{
    # Mock stub for Remove-CsCallingLineIdentity
}

function Remove-CsCallQueue
{
    # Mock stub for Remove-CsCallQueue
}

function Remove-CsClientPolicy
{
    # Mock stub for Remove-CsClientPolicy
}

function Remove-CsConferencingPolicy
{
    # Mock stub for Remove-CsConferencingPolicy
}

function Remove-CsCustomPolicyPackage
{
    # Mock stub for Remove-CsCustomPolicyPackage
}

function Remove-CsDefaultCatalogApp
{
    # Mock stub for Remove-CsDefaultCatalogApp
}

function Remove-CsExternalAccessPolicy
{
    # Mock stub for Remove-CsExternalAccessPolicy
}

function Remove-CsExternalUserCommunicationPolicy
{
    # Mock stub for Remove-CsExternalUserCommunicationPolicy
}

function Remove-CsGlobalCatalogApp
{
    # Mock stub for Remove-CsGlobalCatalogApp
}

function Remove-CsGroupPolicyAssignment
{
    # Mock stub for Remove-CsGroupPolicyAssignment
}

function Remove-CsHuntGroup
{
    # Mock stub for Remove-CsHuntGroup
}

function Remove-CsHybridPSTNSite
{
    # Mock stub for Remove-CsHybridPSTNSite
}

function Remove-CsHybridTelephoneNumber
{
    # Mock stub for Remove-CsHybridTelephoneNumber
}

function Remove-CsInboundBlockedNumberPattern
{
    # Mock stub for Remove-CsInboundBlockedNumberPattern
}

function Remove-CsInboundExemptNumberPattern
{
    # Mock stub for Remove-CsInboundExemptNumberPattern
}

function Remove-CsMobilityPolicy
{
    # Mock stub for Remove-CsMobilityPolicy
}

function Remove-CsOnlineApplicationEndpoint
{
    # Mock stub for Remove-CsOnlineApplicationEndpoint
}

function Remove-CsOnlineApplicationInstanceAssociation
{
    # Mock stub for Remove-CsOnlineApplicationInstanceAssociation
}

function Remove-CsOnlineAudioConferencingRoutingPolicy
{
    # Mock stub for Remove-CsOnlineAudioConferencingRoutingPolicy
}

function Remove-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Remove-CsOnlineDialInConferencingTenantSettings
}

function Remove-CsOnlineLisCivicAddress
{
    # Mock stub for Remove-CsOnlineLisCivicAddress
}

function Remove-CsOnlineLisLocation
{
    # Mock stub for Remove-CsOnlineLisLocation
}

function Remove-CsOnlineLisPort
{
    # Mock stub for Remove-CsOnlineLisPort
}

function Remove-CsOnlineLisSubnet
{
    # Mock stub for Remove-CsOnlineLisSubnet
}

function Remove-CsOnlineLisSwitch
{
    # Mock stub for Remove-CsOnlineLisSwitch
}

function Remove-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Remove-CsOnlineLisWirelessAccessPoint
}

function Remove-CsOnlineNumberPortInOrder
{
    # Mock stub for Remove-CsOnlineNumberPortInOrder
}

function Remove-CsOnlinePSTNGateway
{
    # Mock stub for Remove-CsOnlinePSTNGateway
}

function Remove-CsOnlineSchedule
{
    # Mock stub for Remove-CsOnlineSchedule
}

function Remove-CsOnlineTelephoneNumber
{
    # Mock stub for Remove-CsOnlineTelephoneNumber
}

function Remove-CsOnlineVoicemailPolicy
{
    # Mock stub for Remove-CsOnlineVoicemailPolicy
}

function Remove-CsOnlineVoiceRoute
{
    # Mock stub for Remove-CsOnlineVoiceRoute
}

function Remove-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Remove-CsOnlineVoiceRoutingPolicy
}

function Remove-CsOrganizationalAutoAttendant
{
    # Mock stub for Remove-CsOrganizationalAutoAttendant
}

function Remove-CsTeamsAppPermissionPolicy
{
    # Mock stub for Remove-CsTeamsAppPermissionPolicy
}

function Remove-CsTeamsAppPreset
{
    # Mock stub for Remove-CsTeamsAppPreset
}

function Remove-CsTeamsAppSetupPolicy
{
    # Mock stub for Remove-CsTeamsAppSetupPolicy
}

function Remove-CsTeamsCallHoldPolicy
{
    # Mock stub for Remove-CsTeamsCallHoldPolicy
}

function Remove-CsTeamsCallingPolicy
{
    # Mock stub for Remove-CsTeamsCallingPolicy
}

function Remove-CsTeamsCallParkPolicy
{
    # Mock stub for Remove-CsTeamsCallParkPolicy
}

function Remove-CsTeamsChannelsPolicy
{
    # Mock stub for Remove-CsTeamsChannelsPolicy
}

function Remove-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Remove-CsTeamsComplianceRecordingApplication
}

function Remove-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Remove-CsTeamsComplianceRecordingPolicy
}

function Remove-CsTeamsCortanaPolicy
{
    # Mock stub for Remove-CsTeamsCortanaPolicy
}

function Remove-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Remove-CsTeamsEmergencyCallingPolicy
}

function Remove-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Remove-CsTeamsEmergencyCallRoutingPolicy
}

function Remove-CsTeamsFeedbackPolicy
{
    # Mock stub for Remove-CsTeamsFeedbackPolicy
}

function Remove-CsTeamsIPPhonePolicy
{
    # Mock stub for Remove-CsTeamsIPPhonePolicy
}

function Remove-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Remove-CsTeamsMeetingBroadcastPolicy
}

function Remove-CsTeamsMeetingPolicy
{
    # Mock stub for Remove-CsTeamsMeetingPolicy
}

function Remove-CsTeamsMessagingPolicy
{
    # Mock stub for Remove-CsTeamsMessagingPolicy
}

function Remove-CsTeamsMobilityPolicy
{
    # Mock stub for Remove-CsTeamsMobilityPolicy
}

function Remove-CsTeamsNetworkRoamingPolicy
{
    # Mock stub for Remove-CsTeamsNetworkRoamingPolicy
}

function Remove-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Remove-CsTeamsNotificationAndFeedsPolicy
}

function Remove-CsTeamsPinnedApp
{
    # Mock stub for Remove-CsTeamsPinnedApp
}

function Remove-CsTeamsShiftsPolicy
{
    # Mock stub for Remove-CsTeamsShiftsPolicy
}

function Remove-CsTeamsSurvivableBranchAppliance
{
    # Mock stub for Remove-CsTeamsSurvivableBranchAppliance
}

function Remove-CsTeamsSurvivableBranchAppliancePolicy
{
    # Mock stub for Remove-CsTeamsSurvivableBranchAppliancePolicy
}

function Remove-CsTeamsTargetingPolicy
{
    # Mock stub for Remove-CsTeamsTargetingPolicy
}

function Remove-CsTeamsTranslationRule
{
    # Mock stub for Remove-CsTeamsTranslationRule
}

function Remove-CsTeamsUpdateManagementPolicy
{
    # Mock stub for Remove-CsTeamsUpdateManagementPolicy
}

function Remove-CsTeamsVdiPolicy
{
    # Mock stub for Remove-CsTeamsVdiPolicy
}

function Remove-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Remove-CsTeamsVerticalPackagePolicy
}

function Remove-CsTeamsWorkLoadPolicy
{
    # Mock stub for Remove-CsTeamsWorkLoadPolicy
}

function Remove-CsTeamTemplate
{
    # Mock stub for Remove-CsTeamTemplate
}

function Remove-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Remove-CsTenantBlockedNumberExceptionPattern
}

function Remove-CsTenantCatalogApp
{
    # Mock stub for Remove-CsTenantCatalogApp
}

function Remove-CsTenantDialPlan
{
    # Mock stub for Remove-CsTenantDialPlan
}

function Remove-CsTenantNetworkConfiguration
{
    # Mock stub for Remove-CsTenantNetworkConfiguration
}

function Remove-CsTenantNetworkPostalCode
{
    # Mock stub for Remove-CsTenantNetworkPostalCode
}

function Remove-CsTenantNetworkRegion
{
    # Mock stub for Remove-CsTenantNetworkRegion
}

function Remove-CsTenantNetworkSite
{
    # Mock stub for Remove-CsTenantNetworkSite
}

function Remove-CsTenantNetworkSubnet
{
    # Mock stub for Remove-CsTenantNetworkSubnet
}

function Remove-CsTenantTrustedIPAddress
{
    # Mock stub for Remove-CsTenantTrustedIPAddress
}

function Remove-CsTenantUpdateTimeWindow
{
    # Mock stub for Remove-CsTenantUpdateTimeWindow
}

function Remove-CsUserAcp
{
    # Mock stub for Remove-CsUserAcp
}

function Remove-CsVideoInteropServiceProvider
{
    # Mock stub for Remove-CsVideoInteropServiceProvider
}

function Remove-CsVoiceNormalizationRule
{
    # Mock stub for Remove-CsVoiceNormalizationRule
}

function Remove-Team
{
    # Mock stub for Remove-Team
}

function Remove-TeamChannel
{
    # Mock stub for Remove-TeamChannel
}

function Remove-TeamsApp
{
    # Mock stub for Remove-TeamsApp
}

function Remove-TeamUser
{
    # Mock stub for Remove-TeamUser
}

function Search-CsOnlineTelephoneNumberInventory
{
    # Mock stub for Search-CsOnlineTelephoneNumberInventory
}

function Select-CsOnlineTelephoneNumberInventory
{
    # Mock stub for Select-CsOnlineTelephoneNumberInventory
}

function Set-CsApplicationAccessPolicy
{
    # Mock stub for Set-CsApplicationAccessPolicy
}

function Set-CsApplicationMeetingConfiguration
{
    # Mock stub for Set-CsApplicationMeetingConfiguration
}

function Set-CsAutoAttendant
{
    # Mock stub for Set-CsAutoAttendant
}

function Set-CsBroadcastMeetingConfiguration
{
    # Mock stub for Set-CsBroadcastMeetingConfiguration
}

function Set-CsCallingLineIdentity
{
    # Mock stub for Set-CsCallingLineIdentity
}

function Set-CsCallQueue
{
    # Mock stub for Set-CsCallQueue
}

function Set-CsCceApplianceConfigurationReplicationStatus
{
    # Mock stub for Set-CsCceApplianceConfigurationReplicationStatus
}

function Set-CsCceApplianceDeploymentStatus
{
    # Mock stub for Set-CsCceApplianceDeploymentStatus
}

function Set-CsCceApplianceStatus
{
    # Mock stub for Set-CsCceApplianceStatus
}

function Set-CsClientPolicy
{
    # Mock stub for Set-CsClientPolicy
}

function Set-CsConferencingPolicy
{
    # Mock stub for Set-CsConferencingPolicy
}

function Set-CsDefaultCatalogApp
{
    # Mock stub for Set-CsDefaultCatalogApp
}

function Set-CsExternalAccessPolicy
{
    # Mock stub for Set-CsExternalAccessPolicy
}

function Set-CsExternalUserCommunicationPolicy
{
    # Mock stub for Set-CsExternalUserCommunicationPolicy
}

function Set-CsGlobalCatalogApp
{
    # Mock stub for Set-CsGlobalCatalogApp
}

function Set-CsHuntGroup
{
    # Mock stub for Set-CsHuntGroup
}

function Set-CsHybridMediationServer
{
    # Mock stub for Set-CsHybridMediationServer
}

function Set-CsHybridPSTNAppliance
{
    # Mock stub for Set-CsHybridPSTNAppliance
}

function Set-CsHybridPSTNSite
{
    # Mock stub for Set-CsHybridPSTNSite
}

function Set-CsInboundBlockedNumberPattern
{
    # Mock stub for Set-CsInboundBlockedNumberPattern
}

function Set-CsInboundExemptNumberPattern
{
    # Mock stub for Set-CsInboundExemptNumberPattern
}

function Set-CsInternalOnlinePowerShellEndpoint
{
    # Mock stub for Set-CsInternalOnlinePowerShellEndpoint
}

function Set-CsIPPhonePolicy
{
    # Mock stub for Set-CsIPPhonePolicy
}

function Set-CsMeetingConfiguration
{
    # Mock stub for Set-CsMeetingConfiguration
}

function Set-CsMeetingRoom
{
    # Mock stub for Set-CsMeetingRoom
}

function Set-CsMobilityPolicy
{
    # Mock stub for Set-CsMobilityPolicy
}

function Set-CsNetworkConfiguration
{
    # Mock stub for Set-CsNetworkConfiguration
}

function Set-CsOAuthConfiguration
{
    # Mock stub for Set-CsOAuthConfiguration
}

function Set-CsOnlineApplicationEndpoint
{
    # Mock stub for Set-CsOnlineApplicationEndpoint
}

function Set-CsOnlineApplicationInstance
{
    # Mock stub for Set-CsOnlineApplicationInstance
}

function Set-CsOnlineAudioConferencingRoutingPolicy
{
    # Mock stub for Set-CsOnlineAudioConferencingRoutingPolicy
}

function Set-CsOnlineDialInConferencingBridge
{
    # Mock stub for Set-CsOnlineDialInConferencingBridge
}

function Set-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Set-CsOnlineDialInConferencingServiceNumber
}

function Set-CsOnlineDialInConferencingTenantSettings
{
    # Mock stub for Set-CsOnlineDialInConferencingTenantSettings
}

function Set-CsOnlineDialInConferencingUser
{
    # Mock stub for Set-CsOnlineDialInConferencingUser
}

function Set-CsOnlineDialInConferencingUserDefaultNumber
{
    # Mock stub for Set-CsOnlineDialInConferencingUserDefaultNumber
}

function Set-CsOnlineDirectoryUser
{
    # Mock stub for Set-CsOnlineDirectoryUser
}

function Set-CsOnlineEnhancedEmergencyServiceDisclaimer
{
    # Mock stub for Set-CsOnlineEnhancedEmergencyServiceDisclaimer
}

function Set-CsOnlineLisCivicAddress
{
    # Mock stub for Set-CsOnlineLisCivicAddress
}

function Set-CsOnlineLisLocation
{
    # Mock stub for Set-CsOnlineLisLocation
}

function Set-CsOnlineLisPort
{
    # Mock stub for Set-CsOnlineLisPort
}

function Set-CsOnlineLisSubnet
{
    # Mock stub for Set-CsOnlineLisSubnet
}

function Set-CsOnlineLisSwitch
{
    # Mock stub for Set-CsOnlineLisSwitch
}

function Set-CsOnlineLisWirelessAccessPoint
{
    # Mock stub for Set-CsOnlineLisWirelessAccessPoint
}

function Set-CsOnlineNumberPortInOrder
{
    # Mock stub for Set-CsOnlineNumberPortInOrder
}

function Set-CsOnlineNumberPortOutOrderPin
{
    # Mock stub for Set-CsOnlineNumberPortOutOrderPin
}

function Set-CsOnlinePSTNGateway
{
    # Mock stub for Set-CsOnlinePSTNGateway
}

function Set-CsOnlinePstnUsage
{
    # Mock stub for Set-CsOnlinePstnUsage
}

function Set-CsOnlineSchedule
{
    # Mock stub for Set-CsOnlineSchedule
}

function Set-CsOnlineVoiceApplicationInstance
{
    # Mock stub for Set-CsOnlineVoiceApplicationInstance
}

function Set-CsOnlineVoicemailPolicy
{
    # Mock stub for Set-CsOnlineVoicemailPolicy
}

function Set-CsOnlineVoicemailUserSettings
{
    # Mock stub for Set-CsOnlineVoicemailUserSettings
}

function Set-CsOnlineVoiceRoute
{
    # Mock stub for Set-CsOnlineVoiceRoute
}

function Set-CsOnlineVoiceRoutingPolicy
{
    # Mock stub for Set-CsOnlineVoiceRoutingPolicy
}

function Set-CsOnlineVoiceUser
{
    # Mock stub for Set-CsOnlineVoiceUser
}

function Set-CsOnlineVoiceUserBulk
{
    # Mock stub for Set-CsOnlineVoiceUserBulk
}

function Set-CsOrganizationalAutoAttendant
{
    # Mock stub for Set-CsOrganizationalAutoAttendant
}

function Set-CsPrivacyConfiguration
{
    # Mock stub for Set-CsPrivacyConfiguration
}

function Set-CsPushNotificationConfiguration
{
    # Mock stub for Set-CsPushNotificationConfiguration
}

function Set-CsTeamsAcsFederationConfiguration
{
    # Mock stub for Set-CsTeamsAcsFederationConfiguration
}

function Set-CsTeamsAppPermissionPolicy
{
    # Mock stub for Set-CsTeamsAppPermissionPolicy
}

function Set-CsTeamsAppPreset
{
    # Mock stub for Set-CsTeamsAppPreset
}

function Set-CsTeamsAppSetupPolicy
{
    # Mock stub for Set-CsTeamsAppSetupPolicy
}

function Set-CsTeamsCallHoldPolicy
{
    # Mock stub for Set-CsTeamsCallHoldPolicy
}

function Set-CsTeamsCallingPolicy
{
    # Mock stub for Set-CsTeamsCallingPolicy
}

function Set-CsTeamsCallParkPolicy
{
    # Mock stub for Set-CsTeamsCallParkPolicy
}

function Set-CsTeamsChannelsPolicy
{
    # Mock stub for Set-CsTeamsChannelsPolicy
}

function Set-CsTeamsClientConfiguration
{
    # Mock stub for Set-CsTeamsClientConfiguration
}

function Set-CsTeamsComplianceRecordingApplication
{
    # Mock stub for Set-CsTeamsComplianceRecordingApplication
}

function Set-CsTeamsComplianceRecordingPolicy
{
    # Mock stub for Set-CsTeamsComplianceRecordingPolicy
}

function Set-CsTeamsCortanaPolicy
{
    # Mock stub for Set-CsTeamsCortanaPolicy
}

function Set-CsTeamsEducationAssignmentsAppPolicy
{
    # Mock stub for Set-CsTeamsEducationAssignmentsAppPolicy
}

function Set-CsTeamsEmergencyCallingPolicy
{
    # Mock stub for Set-CsTeamsEmergencyCallingPolicy
}

function Set-CsTeamsEmergencyCallRoutingPolicy
{
    # Mock stub for Set-CsTeamsEmergencyCallRoutingPolicy
}

function Set-CsTeamsFeedbackPolicy
{
    # Mock stub for Set-CsTeamsFeedbackPolicy
}

function Set-CsTeamsGuestCallingConfiguration
{
    # Mock stub for Set-CsTeamsGuestCallingConfiguration
}

function Set-CsTeamsGuestMeetingConfiguration
{
    # Mock stub for Set-CsTeamsGuestMeetingConfiguration
}

function Set-CsTeamsGuestMessagingConfiguration
{
    # Mock stub for Set-CsTeamsGuestMessagingConfiguration
}

function Set-CsTeamsIPPhonePolicy
{
    # Mock stub for Set-CsTeamsIPPhonePolicy
}

function Set-CsTeamsMeetingBroadcastConfiguration
{
    # Mock stub for Set-CsTeamsMeetingBroadcastConfiguration
}

function Set-CsTeamsMeetingBroadcastPolicy
{
    # Mock stub for Set-CsTeamsMeetingBroadcastPolicy
}

function Set-CsTeamsMeetingConfiguration
{
    # Mock stub for Set-CsTeamsMeetingConfiguration
}

function Set-CsTeamsMeetingPolicy
{
    # Mock stub for Set-CsTeamsMeetingPolicy
}

function Set-CsTeamsMessagingPolicy
{
    # Mock stub for Set-CsTeamsMessagingPolicy
}

function Set-CsTeamsMigrationConfiguration
{
    # Mock stub for Set-CsTeamsMigrationConfiguration
}

function Set-CsTeamsMobilityPolicy
{
    # Mock stub for Set-CsTeamsMobilityPolicy
}

function Set-CsTeamsNetworkRoamingPolicy
{
    # Mock stub for Set-CsTeamsNetworkRoamingPolicy
}

function Set-CsTeamsNotificationAndFeedsPolicy
{
    # Mock stub for Set-CsTeamsNotificationAndFeedsPolicy
}

function Set-CsTeamsPinnedApp
{
    # Mock stub for Set-CsTeamsPinnedApp
}

function Set-CsTeamsShiftsAppPolicy
{
    # Mock stub for Set-CsTeamsShiftsAppPolicy
}

function Set-CsTeamsShiftsPolicy
{
    # Mock stub for Set-CsTeamsShiftsPolicy
}

function Set-CsTeamsSurvivableBranchAppliance
{
    # Mock stub for Set-CsTeamsSurvivableBranchAppliance
}

function Set-CsTeamsSurvivableBranchAppliancePolicy
{
    # Mock stub for Set-CsTeamsSurvivableBranchAppliancePolicy
}

function Set-CsTeamsTargetingPolicy
{
    # Mock stub for Set-CsTeamsTargetingPolicy
}

function Set-CsTeamsTranslationRule
{
    # Mock stub for Set-CsTeamsTranslationRule
}

function Set-CsTeamsUpdateManagementPolicy
{
    # Mock stub for Set-CsTeamsUpdateManagementPolicy
}

function Set-CsTeamsUpgradeConfiguration
{
    # Mock stub for Set-CsTeamsUpgradeConfiguration
}

function Set-CsTeamsUpgradeStatus
{
    # Mock stub for Set-CsTeamsUpgradeStatus
}

function Set-CsTeamsVdiPolicy
{
    # Mock stub for Set-CsTeamsVdiPolicy
}

function Set-CsTeamsVerticalPackagePolicy
{
    # Mock stub for Set-CsTeamsVerticalPackagePolicy
}

function Set-CsTeamsWorkLoadPolicy
{
    # Mock stub for Set-CsTeamsWorkLoadPolicy
}

function Set-CsTenantBlockedCallingNumbers
{
    # Mock stub for Set-CsTenantBlockedCallingNumbers
}

function Set-CsTenantBlockedNumberExceptionPattern
{
    # Mock stub for Set-CsTenantBlockedNumberExceptionPattern
}

function Set-CsTenantCatalogApp
{
    # Mock stub for Set-CsTenantCatalogApp
}

function Set-CsTenantDialPlan
{
    # Mock stub for Set-CsTenantDialPlan
}

function Set-CsTenantFederationConfiguration
{
    # Mock stub for Set-CsTenantFederationConfiguration
}

function Set-CsTenantHybridConfiguration
{
    # Mock stub for Set-CsTenantHybridConfiguration
}

function Set-CsTenantMigrationConfiguration
{
    # Mock stub for Set-CsTenantMigrationConfiguration
}

function Set-CsTenantNetworkConfiguration
{
    # Mock stub for Set-CsTenantNetworkConfiguration
}

function Set-CsTenantNetworkPostalCode
{
    # Mock stub for Set-CsTenantNetworkPostalCode
}

function Set-CsTenantNetworkRegion
{
    # Mock stub for Set-CsTenantNetworkRegion
}

function Set-CsTenantNetworkSite
{
    # Mock stub for Set-CsTenantNetworkSite
}

function Set-CsTenantNetworkSubnet
{
    # Mock stub for Set-CsTenantNetworkSubnet
}

function Set-CsTenantPublicProvider
{
    # Mock stub for Set-CsTenantPublicProvider
}

function Set-CsTenantTrustedIPAddress
{
    # Mock stub for Set-CsTenantTrustedIPAddress
}

function Set-CsTenantUpdateTimeWindow
{
    # Mock stub for Set-CsTenantUpdateTimeWindow
}

function Set-CsUCPhoneConfiguration
{
    # Mock stub for Set-CsUCPhoneConfiguration
}

function Set-CsUser
{
    # Mock stub for Set-CsUser
}

function Set-CsUserAcp
{
    # Mock stub for Set-CsUserAcp
}

function Set-CsUserPstnSettings
{
    # Mock stub for Set-CsUserPstnSettings
}

function Set-CsUserServicesPolicy
{
    # Mock stub for Set-CsUserServicesPolicy
}

function Set-CsVideoInteropServiceProvider
{
    # Mock stub for Set-CsVideoInteropServiceProvider
}

function Set-CsVoiceNormalizationRule
{
    # Mock stub for Set-CsVoiceNormalizationRule
}

function Set-Team
{
    # Mock stub for Set-Team
}

function Set-TeamArchivedState
{
    # Mock stub for Set-TeamArchivedState
}

function Set-TeamChannel
{
    # Mock stub for Set-TeamChannel
}

function Set-TeamPicture
{
    # Mock stub for Set-TeamPicture
}

function Set-TeamsApp
{
    # Mock stub for Set-TeamsApp
}

function Start-CsExMeetingMigration
{
    # Mock stub for Start-CsExMeetingMigration
}

function Switch-CsOnlineApplicationEndpoint
{
    # Mock stub for Switch-CsOnlineApplicationEndpoint
}

function Sync-CsOnlineApplicationInstance
{
    # Mock stub for Sync-CsOnlineApplicationInstance
}

function Test-CsEffectiveTenantDialPlan
{
    # Mock stub for Test-CsEffectiveTenantDialPlan
}

function Test-CsInboundBlockedNumberPattern
{
    # Mock stub for Test-CsInboundBlockedNumberPattern
}

function Test-CsOnlineCarrierPortabilityIn
{
    # Mock stub for Test-CsOnlineCarrierPortabilityIn
}

function Test-CsOnlineLisCivicAddress
{
    # Mock stub for Test-CsOnlineLisCivicAddress
}

function Test-CsOnlinePortabilityIn
{
    # Mock stub for Test-CsOnlinePortabilityIn
}

function Test-CsVoiceNormalizationRule
{
    # Mock stub for Test-CsVoiceNormalizationRule
}

function Unregister-CsHybridPSTNAppliance
{
    # Mock stub for Unregister-CsHybridPSTNAppliance
}

function Unregister-CsOnlineDialInConferencingServiceNumber
{
    # Mock stub for Unregister-CsOnlineDialInConferencingServiceNumber
}

function Update-CsAutoAttendant
{
    # Mock stub for Update-CsAutoAttendant
}

function Update-CsCustomPolicyPackage
{
    # Mock stub for Update-CsCustomPolicyPackage
}

function Update-CsOrganizationalAutoAttendant
{
    # Mock stub for Update-CsOrganizationalAutoAttendant
}

function Update-CsTeamTemplate
{
    # Mock stub for Update-CsTeamTemplate
}

function Update-CsTenantMeetingUrl
{
    # Mock stub for Update-CsTenantMeetingUrl
}

